### ISSUE TITLE
relationships not created

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#103]
It says for the transcript only that it created 125 nodes 71 rels but there are no 71 rels in the graph.

![Bildschirmfoto 2024-03-08 um 21 05 27](https://github.com/neo4j-labs/llm-graph-builder/assets/67427/c79e81de-be8a-4a67-8dd6-b56d04457cf9)
![Bildschirmfoto 2024-03-08 um 21 09 44](https://github.com/neo4j-labs/llm-graph-builder/assets/67427/414ae43d-953d-4777-a2d5-ab1317f21aa2)

**Comment by aashipandya** [comment]
Done
