### ISSUE TITLE
Connect Wikipedia nodes to Document/Chunks

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#104]
I saw that the wikipedia nodes are not connected to any chunks or documents
I think we should have the wikipedia page as `Document` node and _if we have_ `Chunk` nodes with embeddings like with the other Sources

This query should show the knowledge graph sourced from document nodes (but not the documents or chunks themselves)

```cypher
MATCH (d:Document) WITH d ORDER BY d.createdAt DESC LIMIT 10
MATCH (d)<-[:PART_OF]-(c:Chunk)-[:HAS_ENTITY]->(entity) 
RETURN entity, [related = (entity)--(:!Chunk) | related] as rels
```

*Mid term we should add Wikipedia as another source* like Youtube and not mix the two up.

**Comment by aashipandya** [comment]
Done
