### ISSUE TITLE
Data ingestion flow attempts to assign multiple relationship types to a single relationship

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/llm-graph-builder#108]
See screenshot below.
A fix for this would be to create an individual relationship for each of the comma separated tags in the type:
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/1754968/ee5b7b23-f02e-4aad-b8d7-5a2944d6d798)

**Comment by aashipandya** [comment]
Fixed
