### ISSUE TITLE
Frontend Bug Fixes

### ISSUE THREAD

**Issue by kartikpersistent** [neo4j-labs/llm-graph-builder#160]

**Comment by jexp** [comment]
Can you add a bit more description and title to these issues, we now have 3  or so that are called "Frontend Bug fixes"

**Comment by kartikpersistent** [comment]
> Can you add a bit more description and title to these issues, we now have 3 or so that are called "Frontend Bug fixes"

By mistake prakriti and I created two issues I will close the duplicate issues.

**Comment by prakriti-solankey** [comment]
Completed and merged
