### ISSUE TITLE
Bug -  All Chunks have the same text and embedding properties

### ISSUE THREAD

**Issue by zach-blumenfeld** [neo4j-labs/llm-graph-builder#181]
Using prod deployment link.  The Chunk nodes connect to different extracted entities but the text and embedding properties are the same on all of them. If I had to guess, it looks like the last text chunk is overwriting the properties for all of them. 

To reproduce:
- youtube link: https://www.youtube.com/watch?v=ddB20U1hQt0
- Additional Wiki Sources: "Elizabeth I"
- Use GPT 3.5

![Screenshot 2024-03-31 at 1 00 47 PM](https://github.com/neo4j-labs/llm-graph-builder/assets/89669746/5751f360-d1b1-4539-8888-e3c892b04870)
![Screenshot 2024-03-31 at 1 00 36 PM](https://github.com/neo4j-labs/llm-graph-builder/assets/89669746/2690b786-45a5-4dc8-8cb0-c6cd5ceca41a)
![Screenshot 2024-03-31 at 12 59 54 PM](https://github.com/neo4j-labs/llm-graph-builder/assets/89669746/1de4280e-9478-49c6-9587-cd0de18ad0f6)

**Comment by aashipandya** [comment]
Fixed
