### ISSUE TITLE
Backend configuration

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#2]
can we make all environment variables uppercase.

and add a section to the backend readme on configuration and the env file.

also call out in the file and readme what is optional and what can be overriden e.g. from the client.

It should be more aligned with the usual style of config variables that we use elsewhere:

```
#OPENAI_API_KEY="sk-..."
DIFFBOT_API_KEY=""
NEO4J_URI=""
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD=""
```

**Comment by praveshkumar1988** [comment]
Done
