### ISSUE TITLE
the generated connect URL is wrong

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#229]
@prakriti-solankey the generated connect URL is wrong, it puts the username before the protocol and appends the port twice, which breaks the "open graph" action.

`decodeURIComponent('neo4j%40neo4j%2Bs%3A%2F%[2F04a02223.databases.neo4j.io](http://2F04a02223.databases.neo4j.io)%3A7687%253A7687')`

-> `'neo4j@neo4j+s://04a02223.databases.neo4j.io:7687%3A7687'`

occurred on the dev-deployment

**Comment by prakriti-solankey** [comment]
merged to main
