### ISSUE TITLE
neo4j-nvl packages not found

### ISSUE THREAD

**Issue by pythinker** [neo4j-labs/llm-graph-builder#261]
While running **docker-compose up --build**, I get this error message:

ERROR [build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react
error An unexpected error occurred: "https://registry.yarnpkg.com/@neo4j-nvl%2finteraction-handlers: Not found"

Are the **neo4j-nvl/interaction-handlers**, **neo4j-nvl/core**, and **neo4j-nvl/react** private packages?

**Comment by nickknyc** [comment]
well - the readme is not updated... what is the workaround please...

**Comment by cip22** [comment]
I have the same issue.

**Comment by kartikpersistent** [comment]
it is going to be public soon

**Comment by msenechal** [comment]
For transparency and clarity, this neo4j-nvl package is the library used for the graph rendering visualization (same one used in other Neo4j tools), which was an internal (private) library.
As Kartik mentioned, it will be public (very) soon, once that is public we will update the source to use the public package and that will fix this issue. (Once done we will also update this issue so you get notified)

**Comment by swanandbagve** [comment]
Till that time is it possible to have any workaround to get the setup complete ?

**Comment by ernesttan1976** [comment]
same error I'm having

**Comment by msenechal** [comment]
Hi all,
The lib for the graph visualization should become public soon, in the meantime, I provided [a small fix here](https://github.com/msenechal/llm-graph-builder/tree/tmp/issue-261)

Which essentially:
- Remove the private package
- Remove the graph visualisation in the GraphView component and replace it with a tmp text

**Comment by msenechal** [comment]
Hi @swanandbagve , Seeing your log, it seems that you are deploying through docker (The fix I made was only working for if you run through npm ; npm run dev, apologize if I wasn't clear)
I've updated that same branch to remove the few bits that were still present in the dockerfile and other places that would prevent the npm run build to succeed.
I've tested both yarn run build and docker build, both works fine now, let me know if you are still facing the issue

**Comment by swanandbagve** [comment]
Hi @msenechal ,
i get this error now on trying to start the docker container. i am not using GCP not google colab
backend   |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
backend   |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
backend   |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
backend   |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
backend   |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
backend   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend   |   File "/code/score.py", line 40, in <module>
backend   |     add_routes(app,ChatVertexAI(), path="/vertexai")
backend   |   File "/usr/local/lib/python3.10/site-packages/langchain_google_vertexai/chat_models.py", line 517, in __init__
backend   |     super().__init__(**kwargs)
backend   |   File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 339, in __init__
backend   |     values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
backend   |   File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 1100, in validate_model
backend   |     values = validator(cls_, values)
backend   |   File "/usr/local/lib/python3.10/site-packages/langchain_google_vertexai/chat_models.py", line 567, in validate_environment
backend   |     values["client"] = model_cls.from_pretrained(generative_model_name)
backend   |   File "/usr/local/lib/python3.10/site-packages/vertexai/_model_garden/_model_garden_models.py", line 291, in from_pretrained
backend   |     raise auth_exceptions.GoogleAuthError(credential_exception_str) from e
backend   | google.auth.exceptions.GoogleAuthError:
backend   | Unable to authenticate your request.
backend   | Depending on your runtime environment, you can complete authentication by:
backend   | - if in local JupyterLab instance: `!gcloud auth login`
backend   | - if in Colab:
backend   |     -`from google.colab import auth`
backend   |     -`auth.authenticate_user()`
backend   | - if in service account or other: please follow guidance in https://cloud.google.com/docs/authentication
backend exited with code 1

**Comment by msenechal** [comment]
Hi @swanandbagve , That is because in our app, we do have the support for gemini/VertexAI (which would require you to setup the gcp env)
If you don't need the gemini/VertexAI integration, and only want to play with openAI, you can simply comment out this line:

In score.py , line 40: 
#add_routes(app,ChatVertexAI(), path="/vertexai")

Don't forget to:
- Change your LLM Models env variable to remove gemini: export LLM_MODELS="Diffbot,OpenAI GPT 3.5,OpenAI GPT 4"
- Rebuild the docker images (docker-compose build)

**Comment by ernesttan1976** [comment]
may I know how do I avoid using Diffbot and use OpenAI instead?

**Comment by prakriti-solankey** [comment]
> * Change your LLM Models env variable to remove gemini: export LLM_MODELS="Diffbot,OpenAI GPT 3.5,OpenAI GPT 4"

Change your LLM Models env variable to remove gemini: export LLM_MODELS="Diffbot,OpenAI GPT 3.5,OpenAI GPT 4"
Rebuild the docker images (docker-compose build)

**Comment by msenechal** [comment]
Hi all,
FYI, the library [Neo4j Visualization Library](https://neo4j.com/deployment-center/#integrations-tab) as been released
I've made the switch and this has been merged on the DEV branch https://github.com/neo4j-labs/llm-graph-builder/pull/299
