### ISSUE TITLE
Chat pop-up button

### ISSUE THREAD

**Issue by msenechal** [neo4j-labs/llm-graph-builder#275]
Having the option from the chat interface to open it in a pop-up window so we can have the chatbot interface on a larger display

**Comment by prakriti-solankey** [comment]
@msenechal , 
As per discussion , we have to open this in new tab

**Comment by ashokrs** [comment]
How to open the chatbot on a larger window to enable thumbs up/down and feedback ui ? Does the main branch have this feature already?

**Comment by prakriti-solankey** [comment]
> How to open the chatbot on a larger window to enable thumbs up/down and feedback ui ? Does the main branch have this feature already?

These features are still under development.

**Comment by ashokrs** [comment]
@prakriti-solankey thanks. much appreciated. In one of the youtube videos, I saw @msenechal demo-ed it. It looked sharp and excited about this feature.

**Comment by prakriti-solankey** [comment]
Merged to main
