### ISSUE TITLE
Chatbot extensions

### ISSUE THREAD

**Issue by msenechal** [neo4j-labs/llm-graph-builder#276]
Extension we can add (low effort to implement)
Text to speech
Copy to clipboard (to copy the response)

could be nice but would require some thinking on implementation
re-generate response
thumbs down + providing feedback that is saved to the graph

Something like this
<img width="989" alt="image" src="https://github.com/neo4j-labs/llm-graph-builder/assets/56915224/b9c35600-aaaf-4011-b5a2-66f424a3309b">

**Comment by msenechal** [comment]
+ on the chatbot within the llm builder interface, since the drawer is quite small, to not take too much space, we can set those only to show on hover of the chatbot's messages with a nice transition/animation

**Comment by msenechal** [comment]
From Michael:
we wanted to have a little (i) info button in the chat response bubble so that we can show structured information in a popup when the user clicks on that (like entities used, tokens, errors, sources, and other metadata)

**Comment by ashokrs** [comment]
How do i open this chatbot extension in a new browser tab? IS this feature available on the main branch?

**Comment by kartikpersistent** [comment]
Hi @ashokrs it is still in development we will push it soon
