### ISSUE TITLE
Is it possible to try locally without paying Neo4j license?

### ISSUE THREAD

**Issue by telekoteko** [neo4j-labs/llm-graph-builder#283]
The Bloom service is accessible without paying for a Bloom Server license?
I would like to try and show to my company the results.

**Comment by cip22** [comment]
I don't know about Bloom, but you can use the community edition of neo4j locally.

**Comment by msenechal** [comment]
Hi @telekoteko 
We are not using bloom for the vizualisation, we use a library called NVL (which is the same one used in bloom, hence probably the confusion)
The license of the library permits its use for valid Neo4j EE license which include Enterprise but also Neo4j Desktop and Aura (Free, Pro or EE)

**Comment by prakriti-solankey** [comment]
> @prakriti-solankey @karanchellani can we close this issue? thanks!

Sure @msenechal
