### ISSUE TITLE
Backend API

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#3]
change the API name from /predict to `/extract`
- spell out knowledge graph in the description

- rename the body object in the docs to something more consistent and descriptive from `Body_kg_creation_predict_post`

also add metadata about the file:

- filename
- file-size
- if available file date
- store those a `:Source` node (or equivalent if the graph transformer already creates a metadata node) in the graph

and in the response at least prepare the numeric `processingTime` and `nodeCount` and `relationshipCount` response fields
and `status` and `errorMessage`

**Comment by karanchellani** [comment]
@jexp can you tell us exactly what you expect when you say: 1.spell out knowledge graph in the description

2. rename the body object in the docs to something more consistent and descriptive from Body_kg_creation_predict_post

**Comment by praveshkumar1988** [comment]
@jexp Can you please explain what you mean : spell out knowledge graph in the description

**Comment by jexp** [comment]
I mean that the API spec is a bit terse: e.g. it says `kg` instead of `knowledge graph`

and the name of the body payload should be something like `extract_graph_from_file` or something like that.
