### ISSUE TITLE
Ran the docker image but unable to connect to front end UI

### ISSUE THREAD

**Issue by swanandbagve** [neo4j-labs/llm-graph-builder#301]
Get no error when i run the code as shown below 

but on trying to access http://localhost:5173/
get message 
This page isn’t working right now

C:\neo4j\llm-graph-builder-tmp-issue-261\llm-graph-builder-tmp-issue-261>set LLM_MODELS="Diffbot,OpenAI GPT 3.5,OpenAI GPT 4"

C:\neo4j\llm-graph-builder-tmp-issue-261\llm-graph-builder-tmp-issue-261>docker-compose build
time="2024-05-09T08:58:40Z" level=warning msg="The \"LANGCHAIN_PROJECT\" variable is not set. Defaulting to a blank string."
time="2024-05-09T08:58:40Z" level=warning msg="The \"LANGCHAIN_API_KEY\" variable is not set. Defaulting to a blank string."
time="2024-05-09T08:58:40Z" level=warning msg="The \"BLOOM_URL\" variable is not set. Defaulting to a blank string."
time="2024-05-09T08:58:40Z" level=warning msg="The \"REACT_APP_SOURCES\" variable is not set. Defaulting to a blank string."
[+] Building 5.2s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.3s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.2s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.10                                                     4.2s
 => [1/4] FROM docker.io/library/python:3.10@sha256:f75ded7bbc9b0318261c8abdc4501382a57f21b204e40af641eacd41cd8c8  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 1.21kB                                                                                0.0s
 => CACHED [2/4] WORKDIR /code                                                                                     0.0s
 => CACHED [3/4] COPY . /code                                                                                      0.0s
 => CACHED [4/4] RUN apt-get update     && apt-get install -y libgl1-mesa-glx cmake     && apt-get install -y pop  0.0s
 => exporting to image                                                                                             0.2s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:da407fb05cc25716c05122c333a3db7d0374e0ad069c7a8dc61382dace379caf                       0.0s
 => => naming to docker.io/library/llm-graph-builder-tmp-issue-261-backend                                         0.0s
[+] Building 3.6s (15/15) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.2s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.3s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                    2.8s
 => [internal] load metadata for docker.io/library/node:20                                                         2.2s
 => [build 1/6] FROM docker.io/library/node:20@sha256:b6e7fef05c7609784c320e5c746aaf8d49221ec0eb3c1242fb673099511  0.0s
 => [internal] load build context                                                                                  0.2s
 => => transferring context: 4.08kB                                                                                0.0s
 => [stage-1 1/3] FROM docker.io/library/nginx:alpine@sha256:516475cc129da42866742567714ddc681e5eed7b9ee0b9e9c015  0.0s
 => CACHED [build 2/6] WORKDIR /app                                                                                0.0s
[+] Building 4.0s (23/23) FINISHED
 => [llm-graph-builder-tmp-issue-261-frontend internal] load build definition from Dockerfile                                                                          0.1s
 => => transferring dockerfile: 32B                                                                                                                                    0.0s
 => [llm-graph-builder-tmp-issue-261-frontend internal] load .dockerignore                                                                                             0.1s
 => => transferring context: 34B                                                                                                                                       0.0s
 => [llm-graph-builder-tmp-issue-261-backend internal] load build definition from Dockerfile                                                                           0.4s
 => => transferring dockerfile: 32B                                                                                                                                    0.0s
 => [llm-graph-builder-tmp-issue-261-backend internal] load .dockerignore                                                                                              0.4s
 => => transferring context: 2B                                                                                                                                        0.0s
 => [llm-graph-builder-tmp-issue-261-frontend internal] load metadata for docker.io/library/nginx:alpine                                                               3.1s
 => [llm-graph-builder-tmp-issue-261-frontend internal] load metadata for docker.io/library/node:20                                                                    2.6s
 => [llm-graph-builder-tmp-issue-261-backend internal] load metadata for docker.io/library/python:3.10                                                                 2.2s
 => [llm-graph-builder-tmp-issue-261-backend internal] load build context                                                                                              0.1s
 => => transferring context: 1.21kB                                                                                                                                    0.0s
 => [llm-graph-builder-tmp-issue-261-backend 1/4] FROM docker.io/library/python:3.10@sha256:f75ded7bbc9b0318261c8abdc4501382a57f21b204e40af641eacd41cd8c8bfb           0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-backend 2/4] WORKDIR /code                                                                                                 0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-backend 3/4] COPY . /code                                                                                                  0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-backend 4/4] RUN apt-get update     && apt-get install -y libgl1-mesa-glx cmake     && apt-get install -y poppler-utils    0.0s
 => [llm-graph-builder-tmp-issue-261-frontend] exporting to image                                                                                                      0.4s
 => => exporting layers                                                                                                                                                0.0s
 => => writing image sha256:da407fb05cc25716c05122c333a3db7d0374e0ad069c7a8dc61382dace379caf                                                                           0.1s
 => => naming to docker.io/library/llm-graph-builder-tmp-issue-261-backend                                                                                             0.0s
 => => writing image sha256:bda0cf8de7203cc074598651a08e0db508803edd2866b676e427577316674947                                                                           0.0s
 => => naming to docker.io/library/llm-graph-builder-tmp-issue-261-frontend                                                                                            0.0s
 => [llm-graph-builder-tmp-issue-261-frontend build 1/6] FROM docker.io/library/node:20@sha256:b6e7fef05c7609784c320e5c746aaf8d49221ec0eb3c1242fb673099511b0583        0.0s
 => [llm-graph-builder-tmp-issue-261-frontend stage-1 1/3] FROM docker.io/library/nginx:alpine@sha256:516475cc129da42866742567714ddc681e5eed7b9ee0b9e9c015e464b4221a0  0.0s
 => [llm-graph-builder-tmp-issue-261-frontend internal] load build context                                                                                             0.1s
 => => transferring context: 4.08kB                                                                                                                                    0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-frontend build 2/6] WORKDIR /app                                                                                           0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-frontend build 3/6] COPY package.json  yarn.lock ./                                                                        0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-frontend build 4/6] RUN yarn install                                                                                       0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-frontend build 5/6] COPY . ./                                                                                              0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-frontend build 6/6] RUN yarn run build                                                                                     0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-frontend stage-1 2/3] COPY --from=build /app/dist /usr/share/nginx/html                                                    0.0s
 => CACHED [llm-graph-builder-tmp-issue-261-frontend stage-1 3/3] COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf                                                 0.0s
[+] Running 2/2
 - Container backend   Recreated                                                                                                                                       0.6s
 - Container frontend  Recreated                                                                                                                                       0.7s
Attaching to backend, frontend
frontend  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
frontend  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
frontend  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
frontend  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
frontend  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
frontend  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
frontend  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
frontend  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
frontend  | /docker-entrypoint.sh: Configuration complete; ready for start up
frontend  | 2024/05/09 09:03:37 [notice] 1#1: using the "epoll" event method
frontend  | 2024/05/09 09:03:37 [notice] 1#1: nginx/1.25.5
frontend  | 2024/05/09 09:03:37 [notice] 1#1: built by gcc 13.2.1 20231014 (Alpine 13.2.1_git20231014)
frontend  | 2024/05/09 09:03:37 [notice] 1#1: OS: Linux 5.15.49-linuxkit
frontend  | 2024/05/09 09:03:37 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
frontend  | 2024/05/09 09:03:37 [notice] 1#1: start worker processes
frontend  | 2024/05/09 09:03:37 [notice] 1#1: start worker process 29
frontend  | 2024/05/09 09:03:37 [notice] 1#1: start worker process 30
backend   | 2024-05-09 09:03:50,454 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
modules.json: 100%|██████████| 349/349 [00:00<00:00, 865kB/s]
config_sentence_transformers.json: 100%|██████████| 116/116 [00:00<00:00, 150kB/s]
README.md: 100%|██████████| 10.7k/10.7k [00:00<00:00, 11.8MB/s]
sentence_bert_config.json: 100%|██████████| 53.0/53.0 [00:00<00:00, 42.9kB/s]
config.json: 100%|██████████| 612/612 [00:00<00:00, 2.65MB/s]
model.safetensors: 100%|██████████| 90.9M/90.9M [00:02<00:00, 35.0MB/s]
tokenizer_config.json: 100%|██████████| 350/350 [00:00<00:00, 895kB/s]
vocab.txt: 100%|██████████| 232k/232k [00:00<00:00, 1.36MB/s]
tokenizer.json: 100%|██████████| 466k/466k [00:00<00:00, 14.2MB/s]
special_tokens_map.json: 100%|██████████| 112/112 [00:00<00:00, 344kB/s]
1_Pooling/config.json: 100%|██████████| 190/190 [00:00<00:00, 505kB/s]
backend   | 2024-05-09 09:03:58,674 - Use pytorch device_name: cpu
backend   | 2024-05-09 09:03:58,679 - Embedding: Using SentenceTransformer , Dimension:384
backend   | INFO:     Started server process [1]
backend   | INFO:     Waiting for application startup.
backend   | INFO:     Application startup complete.
backend   | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by msenechal** [comment]
Hi @swanandbagve , thanks for reporting the issue
It appears because the frontend Dockerfile expose the frontend through nginx on 8080
Where the docker-compose expose the port 5173.
I provided the fix here: https://github.com/neo4j-labs/llm-graph-builder/pull/305
@prakriti-solankey @karanchellani
