### ISSUE TITLE
Getting this error: failed to solve: process "/bin/sh -c yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by chinmaydeshpandecaxsol** [neo4j-labs/llm-graph-builder#304]
time="2024-05-13T11:14:16+05:30" level=warning msg="The \"LANGCHAIN_PROJECT\" variable is not set. Defaulting to a blank string."
time="2024-05-13T11:14:16+05:30" level=warning msg="The \"LANGCHAIN_API_KEY\" variable is not set. Defaulting to a blank string."
time="2024-05-13T11:14:16+05:30" level=warning msg="The \"BLOOM_URL\" variable is not set. Defaulting to a blank string."
time="2024-05-13T11:14:16+05:30" level=warning msg="The \"REACT_APP_SOURCES\" variable is not set. Defaulting to a blank string."
time="2024-05-13T11:14:16+05:30" level=warning msg="C:\\Users\\Admin\\Downloads\\llm-graph-builder-main\\llm-graph-builder-main\\docker-compose.yml: `version` is obsolete"
[+] Building 5.8s (19/24)                                                                                                                                                                             docker:default
 => [backend internal] load build definition from Dockerfile                                                                                                                                                    0.0s
 => => transferring dockerfile: 479B                                                                                                                                                                            0.0s
 => [backend internal] load metadata for docker.io/library/python:3.10                                                                                                                                          2.0s 
 => [backend internal] load .dockerignore                                                                                                                                                                       0.0s 
 => => transferring context: 2B                                                                                                                                                                                 0.0s 
 => [backend 1/4] FROM docker.io/library/python:3.10@sha256:f75ded7bbc9b0318261c8abdc4501382a57f21b204e40af641eacd41cd8c8bfb                                                                                    0.0s 
 => [backend internal] load build context                                                                                                                                                                       0.3s 
 => => transferring context: 678.01kB                                                                                                                                                                           0.2s 
 => CACHED [backend 2/4] WORKDIR /code                                                                                                                                                                          0.0s 
 => CACHED [backend 3/4] COPY . /code                                                                                                                                                                           0.0s 
 => CACHED [backend 4/4] RUN apt-get update     && apt-get install -y libgl1-mesa-glx cmake     && apt-get install -y poppler-utils     && apt install -y tesseract-ocr     && export LD_LIBRARY_PATH=/usr/lib  0.0s 
 => [backend] exporting to image                                                                                                                                                                                0.0s 
 => => exporting layers                                                                                                                                                                                         0.0s 
 => => writing image sha256:ed37c7cf8d2cabf4d70817640e4eebf0e93cb15bb7a02c3dffed532dcbc10d06                                                                                                                    0.0s 
 => => naming to docker.io/library/llm-graph-builder-main-backend                                                                                                                                               0.0s 
 => [frontend internal] load build definition from Dockerfile                                                                                                                                                   0.0s 
 => => transferring dockerfile: 950B                                                                                                                                                                            0.0s 
 => [frontend internal] load metadata for docker.io/library/nginx:alpine                                                                                                                                        2.0s 
 => [frontend internal] load metadata for docker.io/library/node:20                                                                                                                                             2.0s 
 => [frontend internal] load .dockerignore                                                                                                                                                                      0.0s 
 => => transferring context: 52B                                                                                                                                                                                0.0s 
 => [frontend internal] load build context                                                                                                                                                                      0.0s 
 => => transferring context: 4.00kB                                                                                                                                                                             0.0s 
 => CACHED [frontend stage-1 1/3] FROM docker.io/library/nginx:alpine@sha256:516475cc129da42866742567714ddc681e5eed7b9ee0b9e9c015e464b4221a00                                                                   0.0s 
 => [frontend build 1/7] FROM docker.io/library/node:20@sha256:5e362bbb5ef4c6f6e2c86a27b7269b3b3e4bd8dba16be18037ee7ee4caa8afc1                                                                                 0.0s 
 => CACHED [frontend build 2/7] WORKDIR /app                                                                                                                                                                    0.0s 
 => CACHED [frontend build 3/7] COPY package.json .npmrc  yarn.lock ./                                                                                                                                          0.0s 
 => ERROR [frontend build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react                                                                                                    1.0s 
------
 > [frontend build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react:
0.845 yarn add v1.22.19
0.899 error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
0.899 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
0.899 info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react" did not complete successfully: exit code: 1

**Comment by Luminous-seed** [comment]
The same error I‘m justing having... ![image](https://github.com/neo4j-labs/llm-graph-builder/assets/58999828/a0ed0249-2fa9-4086-b951-b27ab5f8fc14)
