### ISSUE TITLE
Deprecated methods usage

### ISSUE THREAD

**Issue by AravinthR** [neo4j-labs/llm-graph-builder#306]
Hi, 

Raising this issue with one of the notebooks in main "PDF_to_kg_using_OpenAI.ipynb"

Error message - LangChainDeprecationWarning: The function `create_structured_output_chain` was deprecated in LangChain 0.1.1 and will be removed in 0.3.0. Use ChatOpenAI.with_structured_output instead.

Steps to reproduce - 
-- access the notebook
-- run all the sections from the top
-- when executing 8th section, the above error is raised

**Comment by jexp** [comment]
The notebooks were mostly experiments in the actual project we use structured output as part of the llm-graph-transformer 

https://python.langchain.com/v0.1/docs/use_cases/graph/constructing/#llm-graph-transformer
