### ISSUE TITLE
Trying to run the application (DEV Branch) but getting this error: google.auth.exceptions.DefaultCredentialsError

### ISSUE THREAD

**Issue by chinmaydeshpandecaxsol** [neo4j-labs/llm-graph-builder#307]
backend   | 2024-05-13 10:49:01,038 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
backend   | 2024-05-13 10:49:04,220 - Use pytorch device_name: cpu
backend   | 2024-05-13 10:49:04,226 - Embedding: Using SentenceTransformer , Dimension:384
backend   | 2024-05-13 10:49:04,710 - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
backend   | 2024-05-13 10:49:04,713 - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
backend   | 2024-05-13 10:49:04,716 - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
backend   | 2024-05-13 10:49:04,716 - Authentication failed using Compute Engine authentication due to unavailable metadata server.
backend   | Traceback (most recent call last):
backend   |   File "/usr/local/bin/uvicorn", line 8, in <module>
backend   |     sys.exit(main())
backend   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
backend   |     return self.main(*args, **kwargs)
backend   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
backend   |     rv = self.invoke(ctx)
backend   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
backend   |     return ctx.invoke(self.callback, **ctx.params)
backend   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
backend   |     return __callback(*args, **kwargs)
backend   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 416, in main
backend   |     run(
backend   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
backend   |     server.run()
backend   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
backend   |     return asyncio.run(self.serve(sockets=sockets))
backend   |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
backend   |     return loop.run_until_complete(main)
backend   |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
backend   |     return future.result()
backend   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
backend   |     config.load()
backend   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
backend   |     self.loaded_app = import_from_string(self.app)
backend   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend   |     module = importlib.import_module(module_str)
backend   |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
backend   |     return _bootstrap._gcd_import(name[level:], package, level)
backend   |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
backend   |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
backend   |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
backend   |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
backend   |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
backend   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend   |   File "/code/score.py", line 24, in <module>
backend   |     logging_client = gclogger.Client()
backend   |   File "/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/client.py", line 122, in __init__
backend   |     super(Client, self).__init__(
backend   |   File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 320, in __init__
backend   |     _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
backend   |   File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 268, in __init__
backend   |     project = self._determine_default(project)
backend   |   File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
backend   |     return _determine_default_project(project)
backend   |   File "/usr/local/lib/python3.10/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
backend   |     _, project = google.auth.default()
backend   |   File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 691, in default
backend   |     raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
backend   | google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
backend exited with code 1

**Comment by ais-qianhao-liu** [comment]
See #295 to resolve

**Comment by chinmaydeshpandecaxsol** [comment]
@ais-qianhao-liu  Thank you!
