### ISSUE TITLE
Documentation for environment variables and using open AI for graph generation

### ISSUE THREAD

**Issue by swanandbagve** [neo4j-labs/llm-graph-builder#308]
When do we plan to checkin all the code
1)To allow using OpenAI and not just diffbot in generating graph
2)Having the open source version of the visualization library deployed
Currently i am using dev branch but dont have the openAI option for graph creation

Also can we have some documentation on values to be set for various parameters like for optimal results please ?
KNN_MIN_SCORE = 
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""
LANGCHAIN_TRACING_V2 = ""
LANGCHAIN_ENDPOINT = ""
NUMBER_OF_CHUNKS_TO_COMBINE = 
 NUMBER_OF_CHUNKS_ALLOWED

**Comment by kartikpersistent** [comment]
Hi @swanandbagve 

create a env file in frontend root folder to play with llm configuration by default LLM_MODELS should be empty string which will enable all llm's if you want play with specific llm's then mention comma separated value in the LLM_MODELS
**ex:** LLM_MODELS="Diffbot,OpenAI GPT 4"

Same for the sources if you want to give only youtube ,Wikipedia, then provide comma separated values in REACR_APP_SOURCE
**ex:** REACT_APP_SOURCES="youtube,wikipedia"

By Default
REACT_APP_SOURCES=""
LLM_MODELS=""

we will mention these steps in the readme

**Comment by jexp** [comment]
@swanandbagve check out the DEV branch for the latest code.
The `main` branch has the production deployment.

@kartikpersistent can we add them with the comments to the env.example and the readme ?

# minimum score for creating a kNN SIMILAR relationship, e.g. 0.9 
KNN_MIN_SCORE=
# Optional LangSmith API credentials for monitoring & observability https://smith.langchain.com
# LANGCHAIN_API_KEY=""
# LANGCHAIN_PROJECT=""
# LANGCHAIN_TRACING_V2="true"
# LANGCHAIN_ENDPOINT=""

# For entity extraction we combine multiple chunks, e.g 4 for processing
NUMBER_OF_CHUNKS_TO_COMBINE=
# Maximum number of chunks per document processed, e.g. for public hosting to limit LLM costs  & processing time
NUMBER_OF_CHUNKS_ALLOWED=
```

**Comment by kartikpersistent** [comment]
Hi @jexp  already added in the linked pr we will merge it soon

**Comment by kartikpersistent** [comment]
> The code public visualization library is coming this week to DEV.

public version is already in DEV

**Comment by ashokrs** [comment]
I am o with using OPENAI_API_KEY to generate graph.  Can I ignore DIFFBOT_API_KEY completely ?

**Comment by burakakca** [comment]
I'm trying to run your project but, envirement variables are not clear at least for me, can you provide better explanation for readme?

**Comment by aashipandya** [comment]
Done
