### ISSUE TITLE
Drag the legends panel similar to workspace

### ISSUE THREAD

**Issue by prakriti-solankey** [neo4j-labs/llm-graph-builder#327]
Something Like this :
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/156313631/c5d1427a-052e-4a0f-8988-f297610c3fe4)

**Comment by ThatDaveStevens** [comment]
could this also be implemented for the Q&A Chat section?   option to drag and expand beyond its current size

**Comment by jexp** [comment]
For chat we also want to have an popout option, I already asked @msenechal to look into that.

**Comment by msenechal** [comment]
@ThatDaveStevens for the Q&A chat, you can subscribe to this one: https://github.com/neo4j-labs/llm-graph-builder/issues/275

**Comment by prakriti-solankey** [comment]
Merged to Main
