### ISSUE TITLE
NotImplementedError: in the line structured_llm = llm.with_structured_output(schema, include_raw=True)

### ISSUE THREAD

**Issue by SandhiyaGiri** [neo4j-labs/llm-graph-builder#338]
Hello,

I'm not running the whole app. 
I want to build a knowledge graph, run query on the knowledge graph and retrieve result from the LLM.

While executing this line of code 

        # Define chain
        schema = create_simple_model(allowed_nodes, allowed_relationships)
        structured_llm = llm.with_structured_output(schema, include_raw=True)
        self.chain = prompt  | structured_llm

I encountered a NotImplementedError:

![image](https://github.com/neo4j-labs/llm-graph-builder/assets/112756649/7f353e6a-ad86-42d2-9902-64146762ca33)

Here's the llm call :

      llm = AzureChatOpenAI(
         deployment_name="gpt-4",
        openai_api_version="2023-05-15",
        temperature = 0
        )

**Comment by jexp** [comment]
@tomasonjo do you know why `AzureChatOpenAI` would not support structured output in LC?

**Comment by tomasonjo** [comment]
Make sure to use the latest version from the partner library:

```
from langchain_openai import AzureChatOpenAI

AzureChatOpenAI(
    azure_deployment="35-turbo-dev",
    openai_api_version="2023-05-15",
)
```
