### ISSUE TITLE
DEV branch is again giving Failed to replace env in config: ${NPM_TOKEN}

### ISSUE THREAD

**Issue by swanandbagve** [neo4j-labs/llm-graph-builder#345]
=> => extracting sha256:0d0c16747d2c6b6c26c064652afcb964c15f1b1e596ec052b2aa19b83948ae27                                                               1.4s
 => [frontend build 2/7] WORKDIR /app                                                                                                                   2.7s
 => [frontend build 3/7] COPY package.json .npmrc  yarn.lock ./                                                                                         0.2s
 => ERROR [frontend build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react                                            1.6s
------
 > [frontend build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react:
1.274 yarn add v1.22.19
1.334 error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
1.334 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
1.334 info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react" did not complete successfully: exit code: 1

C:\neo4j\llm-graph-builder-dev\llm-graph-builder-dev>

**Comment by kartikpersistent** [comment]
Hi @swanandbagve  can you try by please removing the .npmrc file in docker also in frontend root folder

**Comment by luzidl** [comment]
@swanandbagve I also have the same issue installing now on Linux (Ubuntu), since on Mac did not work (see the other issue I opened). Removing the .npmrc file does not work. It complains the file is missing once you remove it.

**Comment by luzidl** [comment]
@kartikpersistent I did so, but then I get another error:

`[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@neo4j-nvl%2fcore: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
The command '/bin/sh -c yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react' returned a non-zero code: 1
ERROR: Service 'frontend' failed to build : Build failed
`
The Dockerfile in the frontend Dir looks like this now:
COPY package.json yarn.lock ./
# COPY package.json .npmrc  yarn.lock ./

**Comment by kartikpersistent** [comment]
Delete the .npmrc file and in Dockerfile remove the COPY .npmrc part this should fix the error

**Comment by luzidl** [comment]
@kartikpersistent still no luck. Did exactly what you advised above, but still getting this one:

`info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error An unexpected error occurred: "https://registry.yarnpkg.com/@neo4j-nvl%2fcore: Not found".
The command '/bin/sh -c yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react' returned a non-zero code: 1
ERROR: Service 'frontend' failed to build : Build failed`

I also did a new clone to be sure, I had not changed something else. Am I missing a parameter maybe?

**Comment by kartikpersistent** [comment]
Please take the latest pull and switch to DEV for the latest features

**Comment by luzidl** [comment]
Works now with DEV branch on Linux.
