### ISSUE TITLE
App is not responsive, generate graph button doesn't show on narrower screen

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#35]
<img width="1423" alt="Bildschirmfoto 2024-02-07 um 16 34 37" src="https://github.com/neo4j-labs/llm-graph-builder/assets/67427/f97d42f6-e7e4-4c22-829e-a09f53804b40">

Also instead of select LLM it should say "Select Model"

**Comment by prakriti-solankey** [comment]
Handling under ticket [GitHub Issue 32](https://github.com/neo4j-labs/llm-graph-builder/issues/32)

**Comment by prakriti-solankey** [comment]
App UI Correction :
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/156313631/d7475ff5-36c7-40a8-8c68-b43390d6083f)

Also Added table pagination to show files more than 5 on page 2
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/156313631/6cbbb776-1813-4d8c-96ab-c757f12044cd)
