### ISSUE TITLE
Don't rely on the implicit environment variables for OPENAI_API_KEY but pass them explicitely as constructor parameters

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#350]
We already do it in the chat just not in the LLM construction for extraction.

We should have a single helper function to construct the LLM not spread across multiple places

Also add support these:

* `OPENAI_BASE_URL`
* `OPENAI_API_VERSION`
* `OPENAI_PROXY`

**Comment by aashipandya** [comment]
Done
