### ISSUE TITLE
fix the langchain and langchain_community version for deployment

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#352]
latest versions are: langchain 0.2.0 langchain_community: 0.2.0

@abhishekkumar-27 please verify that these versions are working with your integration test

**Comment by abhishekkumar-27** [comment]
All the sources are working fine while executed integration test with latest langchain and langchain_community Version: 0.2.1

**Comment by aashipandya** [comment]
Done
