### ISSUE TITLE
integration test for large file (esp. for upload + chunking)

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#354]
* without needing the LLM just upload + chunk split
* to reproduce the neo4j connecition lost / timeout issues

**Comment by ashokrs** [comment]
I ingested a 400 page pdf file. The graph builder worked fine to create the KB graph and chunks with relationships. However, when I invoke Q&A chat window, I get “Something went wrong” from the BO. and no response. I hooked up the system to point to my local backend server running on port 8000 and got the ERROR that the input content length is set to 16K and the KB schema generated by the pdf is 64K. May I change the LLM to high input content length as the schema is way too large…

**Comment by jexp** [comment]
Hmm for the vector search we don’t send the schema but the entities connected to the top-k chunks. 
yea please try to adjust the context limits. 

@vasanthasaikalluri @tomasonjo something we should take into account
