### ISSUE TITLE
New DEV branch file selection from front end to delete from graph not working for a file stuck in processing state

### ISSUE THREAD

**Issue by swanandbagve** [neo4j-labs/llm-graph-builder#356]
New DEV branch file selection from front end to delete from graph not working for a file stuck in processing state. The file is not actually undergoing processing and seems orphaned

**Comment by kartikpersistent** [comment]
Hi @swanandbagve if you process any large files parallel if you try to upload or process any small files it is too much time we already working on that until please clear the DB and play with small files.

**Comment by aashipandya** [comment]
Now uploading and processing for files is working in parallel in latest release of app.
