### ISSUE TITLE
NotFoundError - Extract Chain Invoke

### ISSUE THREAD

**Issue by sh240524** [neo4j-labs/llm-graph-builder#365]
Hi, when running the [PDF to KG with OpenAI](https://github.com/neo4j-labs/llm-graph-builder/blob/main/experiments/PDF_to_kg_using_OpenAI.ipynb) notebook, I get a NotFoundError. Is there any way to resolve this? Please see the code snippet and error below:

![image](https://github.com/neo4j-labs/llm-graph-builder/assets/170746131/21383fc3-30b4-4579-8979-a22085915fbb)

NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by jexp** [comment]
Make sure the files are also there in the right folder when you run this
relative to where you are running the notebook, or change the path accordingly.

`PyPDFLoader("../data/Football_news.pdf")`
