### ISSUE TITLE
Cannot Generate Graph via uploaded pdf file

### ISSUE THREAD

**Issue by wolfgang-ldc** [neo4j-labs/llm-graph-builder#368]
Tried the on-line version of this really interesting tool https://llm-graph-builder.neo4jlabs.com/ and got stuck on the very first step of generating a graph. I uploaded a pdf file and clicked on Generate graph, then got the error message - Failed to process file Kymera.pdf or LLM unable to parse content file Kymera.pdf  does not exist.
I had tried this a few days ago and it actually did work. Something must have changed.

Thanks in advance.

**Comment by arthcras** [comment]
have the same issue

**Comment by arthcras** [comment]
> We will push the latest prod version today

**Comment by kartikpersistent** [comment]
Hi @arthcras we are working various features so we will deploy to prod by this month end mostly today or tomorrow you can test DEV version here is the [link](https://dev-frontend-dcavk67s4a-uc.a.run.app/)

**Comment by arthcras** [comment]
Hi@karrtikpersistent: update i tested the dev version but large pdf are still hanging, (i tested same files) two weeks ago and all works fine

**Comment by jexp** [comment]
How big are your files? (number of pages)?
Can you provide the files for testing?

**Comment by arthcras** [comment]
Attachment available until Jul 3, 2024
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAVX9iggB_F5eWu3M8t7Ng6cdluuOAdkSs-uK9kj8z-k4ltFq0z6IDhQA%2F%24%7Bf%7D%3Fo%3DAnSyk87kkIrFU9lf9NoVigfDhxToXzcON6xwCUB6NDLd%26v%3D1%26x%3D3%26a%3DCAogK09a3J648Z3JWN8VUO9eRuCNMQjap2tIi_md1ciTflISeBC68qH3_TEYuoKdy4cyIgEAKgkC6AMA_05v-atSBB2W645aBIgOFABqJl5ceAhOZd54WG9PLtkKRC58Fp-mm7rCVcoSnAX3OZvsHMWuqcXdciZr-KHvfHaR58WH2RrA7jduENi-hqHdHn0M4FIPE8CXGE96c5H-sg%26e%3D1720023728%26fl%3D%26r%3D3E6C2E4A-C153-4414-929D-437879333657-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D37BC9E2B-FE67-44C9-ABFD-7E23FAD2A319%26p%3D106%26s%3D92uQAO6CpAUzlZPQta3j0AyJ-8w&uk=nG5dchxhYiY8PnPjuqxhfg&f=Generic%20-%20ngfs_scenarios_technical_documentation_phase_iv_2023.pdf&sz=21955917>Generic - ngfs_scenarios_technical_documentation_phase_iv_2023.pdf
22 MB
HI Michael: Yes off course, pls find attached , best rgds Arthur

**Comment by jexp** [comment]
That's a huge document with 211 pages, can you try with a subset first?
With the first 10 pages I get this result, it extracted 240 nodes and 223 relationships  in 304.89 seconds.

<img width="1254" alt="Bildschirmfoto 2024-06-04 um 14 25 53" src="https://github.com/neo4j-labs/llm-graph-builder/assets/67427/a8db9f97-a968-4f6a-8e92-8632928ee87b">
<img width="1679" alt="Bildschirmfoto 2024-06-04 um 14 25 31" src="https://github.com/neo4j-labs/llm-graph-builder/assets/67427/b117d940-29ea-4007-9560-693fc5901910">

**Comment by arthcras** [comment]
Ok will do thanks; that worked with smaller docu yes i had same result as you but then in stops after 400 nodes or so…Two weeks ago I had several doc with more than 200 pages and it was working quick and good without any issues and problemsI noticed that someone has that same encounter to; had something change in set upKindRgdsArthurSent from my iPhoneOn Jun 4, 2024, at 8:27 AM, Michael Hunger ***@***.***> wrote:﻿
That's a huge document with 211 pages, can you try with a subset first?
With the first 10 pages I get this result, it extracted 240 nodes and 223 relationships  in 304.89 seconds.
Bildschirmfoto.2024-06-04.um.14.25.53.png (view on web)
Bildschirmfoto.2024-06-04.um.14.25.31.png (view on web)
