### ISSUE TITLE
Feature Request: Progress Bar, Disable Disconnect button and Support for Gemini 1.5 Pro and Gemini 1.5 Flash

### ISSUE THREAD

**Issue by sidagarwal04** [neo4j-labs/llm-graph-builder#372]
I would like to request for 3 features in the tool:

1. Progress Bar to know the status of progress done while the tool is processing the data
2. Disable the disconnect button while the data is being processed to avoid accidentally clicking it.
3. Support for Gemini 1.5 Pro and Gemini 1.5 Flash

**Comment by kartikpersistent** [comment]
Hi @sidagarwal04  1,3 are already in progress you can test that in DEV version we didn't added Gemini 1.5 flash yet others we will take it up soon

**Comment by sidagarwal04** [comment]
Sure, noted. Thanks @kartikpersistent!
