### ISSUE TITLE
Duplicate entities & PDF processing fails with 422

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#38]
<img width="1544" alt="Bildschirmfoto 2024-02-07 um 16 16 08" src="https://github.com/neo4j-labs/llm-graph-builder/assets/67427/45a29d51-23f3-4298-81c7-13330dca807f">

I tried to run the app, it still creates duplicates of the file with the same name

and when trying to process the file I get a 422 error

```
backend   | INFO:     172.18.0.1:44740 - "GET /sources_list HTTP/1.1" 200 OK
backend   | INFO:     172.18.0.1:44732 - "GET /health HTTP/1.1" 200 OK
backend   | INFO:     172.18.0.1:44748 - "GET /health HTTP/1.1" 200 OK
backend   | INFO:     172.18.0.1:44754 - "GET /sources_list HTTP/1.1" 200 OK
backend   | INFO:     172.18.0.1:35078 - "POST /sources HTTP/1.1" 200 OK
backend   | INFO:     172.18.0.1:55262 - "POST /extract HTTP/1.1" 422 Unprocessable Entity
```

**Comment by jexp** [comment]
Could be due to not having selected an Model in the drop down 

we should either 

- default to one, or 
- handle the missing config in the backend leniently, or 
- disable graph generation until one is selected but then also indicate that it requires an model to be selected

perhaps we should move the both dropdown + button side-by side (but I'm not a designer)

**Comment by prakriti-solankey** [comment]
Completed file overridden :
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/156313631/009ee44f-3f81-4647-a3dc-b99deb6f8c1a)

Same File with status 'Uploading' and Default values
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/156313631/a9c9c3b9-4347-44bf-9f91-6bfa701d1d05)

Same File with status 'New' and Default values
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/156313631/190298e1-bdea-4199-8e62-01228b13ded2)
