### ISSUE TITLE
Uvicorn service started next steps

### ISSUE THREAD

**Issue by Arnav-99** [neo4j-labs/llm-graph-builder#382]
This isn't an issue, but a question for which I could of no other place to ask for an answer. I currently am able to run the uvicorn service:
<img width="1215" alt="Screen Shot 2024-05-31 at 16 49 55" src="https://github.com/neo4j-labs/llm-graph-builder/assets/113748526/07417c0a-9ec8-4190-ae30-f2596d95add7">

How am I supposed to use the API now? What is the procedure towards being able to use the relevant functions like extract_graph_from_file in code? A clarification would be really helpful! Thanks!

**Comment by jexp** [comment]
@karanchellani these should be covered in the technical/architecture documentation, right?
Can you provide a link?

**Comment by jexp** [comment]
Can you check if this helps

https://neo4j.com/labs/genai-ecosystem/llm-graph-builder-deployment/
