### ISSUE TITLE
Backend API

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#4]
When adding `:Source` nodes to the graph to represent the files, add a `/sources/list` endpoint that returns the list of sources ordered by `updatedAt` descending and returns all the metadata, that was added/updated when creating the nodes

- fileName (for the time being this can be the id - unique constraint)
- fileType
- fileSize
- createdAt
- updatedAt
- processingTime
- status
- errorMessage
- nodeCount
- relationshipCount

**Comment by aashipandya** [comment]
Done
