### ISSUE TITLE
如何打开应用程序

### ISSUE THREAD

**Issue by ck1123456** [neo4j-labs/llm-graph-builder#430]
您好，请问我部署完后端之后怎样才会生成
![微信图片_20240614165810](https://github.com/neo4j-labs/llm-graph-builder/assets/135198170/22235a2e-5af8-42f4-aa51-7a3a65717a83)
这个界面呢

**Comment by ais-qianhao-liu** [comment]
- 首先本地跑起来前后端

- 你得上传文件，让他处理过后，可以用Neo4j客户端连接你的数据库。这个项目自带的viewer不是很好用。

**Comment by ck1123456** [comment]
好的谢谢，请问我前端运行后得到的网址为什么打开出现这样的页面
![Uploading 微信图片_20240618151240.png…]()

**Comment by ais-qianhao-liu** [comment]
你的图片坏了

**Comment by jexp** [comment]
Can you please ask your questions in English, otherwise we can't help you. Thank you!
