### ISSUE TITLE
前端运行

### ISSUE THREAD

**Issue by ck1123456** [neo4j-labs/llm-graph-builder#440]
Hello, could you please tell me why this interface appears when I run the frontend and copy the frontend website? What is the error? Please advise.
![微信图片_20240529151411](https://github.com/neo4j-labs/llm-graph-builder/assets/135198170/ead0a5e5-37d6-475e-9a6d-eb0f7dd2fbf3)

**Comment by jexp** [comment]
This looks more like a python / venv issue, so something we cannot really help you with.
You should also not run as root!
