### ISSUE TITLE
frontend operation

### ISSUE THREAD

**Issue by ck1123456** [neo4j-labs/llm-graph-builder#441]
Hello, could you please tell me why this interface appears when I run the frontend and copy the frontend website? What is the error? Please advise.
![Uploading image.png…]()

**Comment by ck1123456** [comment]
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/135198170/00d19a88-3553-45ae-b431-53722c6c5c97)

**Comment by ck1123456** [comment]
![Uploading 微信图片_20240618164626.png…]()

**Comment by prakriti-solankey** [comment]
Your Images are not uploaded properly to verify the issue.
