### ISSUE TITLE
Adding file with "non-supported" extension results in file larger than 15MB error

### ISSUE THREAD

**Issue by martinohanlon** [neo4j-labs/llm-graph-builder#444]
When you try and add a file which is of an "unsupported" file type e.g. a file which isn't included in the "file types" dialog an error is displayed stating this file is > 15 MB.

I wanted to add text files, in this case AsciiDoc files with an `.adoc` extension, but am unable to do so due to being presented with the error.

If I change the file by adding a `.txt` extension the file can be uploaded.

The same issue is seen with other "unsupported" files types `.md` `.py` `.js` `.css` etc

https://github.com/neo4j-labs/llm-graph-builder/assets/2329501/c3a603a6-0078-47de-b3ab-1eb3a46cde09

**Comment by kartikpersistent** [comment]
Hi @martinohanlon We changed the error message if user want to upload unsupported extensions we are throwing the error
