### ISSUE TITLE
404 on google cloud app

### ISSUE THREAD

**Issue by rawwerks** [neo4j-labs/llm-graph-builder#449]
![CleanShot 2024-06-18 at 07 36 04@2x](https://github.com/neo4j-labs/llm-graph-builder/assets/19483938/2d25086e-41b7-4d6d-b899-278a9c89b32f)

https://devfrontend-dcavk67s4a-uc.a.run.app/ => 404

**Comment by rawwerks** [comment]
is there a hosted version available for testing?

**Comment by kartikpersistent** [comment]
HI @rawwerks  this is the  [DEV link](https://dev-frontend-dcavk67s4a-uc.a.run.app/)
