### ISSUE TITLE
Support for Ollama local LLMs

### ISSUE THREAD

**Issue by leiolay** [neo4j-labs/llm-graph-builder#452]
My organization cannot use OpenAI / Diffbot LLMs. Is there any plan to add support for Ollama local LLMs?

**Comment by jexp** [comment]
Yes it’s on plan

**Comment by carloposo** [comment]
Hello @jexp , I am also interested in this, is there a planned delivery date for it? :)

**Comment by jexp** [comment]
Early next week is the plan 
Cc @aashipandya

**Comment by carloposo** [comment]
> Early next week is the plan Cc @aashipandya

Happy

**Comment by leiolay** [comment]
> Early next week is the plan Cc @aashipandya

That's music to my ears!!!

**Comment by gy850222** [comment]
@jexp I am eagerly looking forward to the release of the Support for Ollama local LLMs version. Will the new version be released in 0.3v or under the tags new_llms or llm_config?

**Comment by aashipandya** [comment]
> @jexp I am eagerly looking forward to the release of the Support for Ollama local LLMs version. Will the new version be released in 0.3v or under the tags new_llms or llm_config?

I will be a new release

**Comment by jexp** [comment]
Yes it will be v3.

But it is already in DEV and you can test it out there, but right now the extraction quality is not great with llama3:7b

**Comment by gy850222** [comment]
@jexp @aashipandya I'm glad to see this reply. I will try to test it in the DEV version later. I have been following how to use models from Ollama to build knowledge graphs with Neo4j. I am also very interested in joining the team to participate in the tuning and testing of this project. Additionally, I am willing to provide technical support for Chinese users.

**Comment by gy850222** [comment]
Thank you very much for the team's hard work and dedication. I have successfully connected Ollama in the DEV version and constructed knowledge graphs from documents using models such as llama3:8b and qwen2:7b. Personally, I feel that the initial results are quite good. I will continue to try optimizations based on any issues I encounter and share my findings. Looking forward to the release of version 3. :)

**Comment by aashipandya** [comment]
New version (v0.3) is released, feel free to explore.

**Comment by xhx1022** [comment]
> @jexp @aashipandya Thank you very much for the team's hard work and dedication. I have successfully connected Ollama in the DEV version and constructed knowledge graphs from documents using models such as llama3:8b and qwen2:7b. Personally, I feel that the initial results are quite good. I will continue to try optimizations based on any issues I encounter and share my findings. Looking forward to the release of version 3. :)非常感谢团队的辛勤工作和奉献精神。我已经在DEV版本中成功连接了Llama，并使用llama3：8b和qwen2：7b等模型从文档中构建了知识图谱。就我个人而言，我觉得初步的结果还算不错。我将继续根据遇到的任何问题尝试优化，并分享我的发现。期待第3版的发布。:)

Could you share how to deploy the local LLM？
