### ISSUE TITLE
Deleting a file fails on local env

### ISSUE THREAD

**Issue by ionuttiplea** [neo4j-labs/llm-graph-builder#465]
I don't know the specifics, I most likely still lack the understanding of the project but, when I try to delete a file I uploaded, this would be the error in docker
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/109800363/2de02b79-79f5-45f3-8b4c-4f4e6435a1c7)
Maybe GCS configuration is mandatory? Is the repository documentation up to date? 
Or is this an issue that needs to be addressed?

**Comment by jexp** [comment]
We will fix

**Comment by punksta** [comment]
Fixed by

adding

from `src.shared.common_fn import delete_uploaded_local_file`

and using          `delete_uploaded_local_file(merged_file_path, file_name)`
instaed  of         `delete_file_from_gcs(BUCKET_UPLOAD,file_name)`

**Comment by kartikpersistent** [comment]
Hi @punksta 
you can use GCS_FILE_CACHE = False variable in the backend env to process the files locally. If it is true the files will be stored in the google cloud storage.

**Comment by punksta** [comment]
It looks like Deleting files doesn't check this flag.

**Comment by praveshkumar1988** [comment]
@punksta Please check the latest code.

**Comment by ionuttiplea** [comment]
> Hi @punksta you can use GCS_FILE_CACHE = False variable in the backend env to process the files locally. If it is true the files will be stored in the google cloud storage.

I did try that yesterday, it didn't help
A temporary solution was commenting this : 
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/109800363/44bb0fee-b616-4d00-9906-0ef24018a7fd)
The function call 
`                delete_file_from_gcs(BUCKET_UPLOAD,file_name)
`
from **backend/src/graphDB_dataAccess.py**

**Comment by ionuttiplea** [comment]
> @punksta Please check the latest code.

I will, as in the update from yesterday another condition has been added
It's cool how fast this was addressed

**Comment by praveshkumar1988** [comment]
Please take the latest pull from GIT, It will look like the below screen shot.
<img width="534" alt="image" src="https://github.com/neo4j-labs/llm-graph-builder/assets/121786590/2c213d96-b2f1-4cec-9e07-7605a8bcd8d4">

**Comment by ionuttiplea** [comment]
It is fixed now, many thanks to everyone involved :100:
