### ISSUE TITLE
Add support for .xlsx files

### ISSUE THREAD

**Issue by blacksmithop** [neo4j-labs/llm-graph-builder#477]
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/60320192/a4e7ecc1-7c9b-41aa-b056-d68a7f267ad8)
When uploading .xls files the Upload Status is stuck at 0%

**Comment by blacksmithop** [comment]
@kartikpersistent I feel like `.xlsx` support could be added
https://github.com/neo4j-labs/llm-graph-builder/blob/e8d0a8b62fff9e2a81413aff48bdb5eba044b57e/frontend/src/components/DataSources/Local/DropZone.tsx#L260

**Comment by kartikpersistent** [comment]
Hi @blacksmithop we will check whether .xlsx extension is supported by UnstructuredFileLoader

**Comment by kartikpersistent** [comment]
Hi @blacksmithop  we added support for xlsx in DEV branch please test and let us know
