### ISSUE TITLE
Frontend Connection Status

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#5]
The front end should indicate if the back-end is running.

Right now it shows the file-drop area if neo4j/the backend is connected but there should be a clearer indication.

**Comment by jexp** [comment]
They are not the same, the 6 is about sending connection information for neo4j to the backend.
5 is about - is the front-end able to connect to the backend.

**Comment by prakriti-solankey** [comment]
@jexp , Sharing a screenshot for reference. Please let us know if the connection information is ok in this way. 


![Image](https://github.com/neo4j-labs/llm-graph-builder/assets/156313631/13f01ca8-9a22-4298-bbce-591f6758b2ae)

**Comment by prakriti-solankey** [comment]
Handled Previously
