### ISSUE TITLE
Should shave unique identity for every Document node?

### ISSUE THREAD

**Issue by ais-qianhao-liu** [neo4j-labs/llm-graph-builder#516]
I see file_name is used to get_current_status_document_node, should we have a unique identity for every Document node? what if we have two node with same fileName.

`def get_current_status_document_node(self, file_name):
        query = """
                MATCH(d:Document {fileName : $file_name}) RETURN d.status AS Status , d.processingTime AS processingTime, 
                d.nodeCount AS nodeCount, d.model as model, d.relationshipCount as relationshipCount,
                d.total_pages AS total_pages, d.total_chunks AS total_chunks , d.fileSize as fileSize, 
                d.is_cancelled as is_cancelled, d.processed_chunk as processed_chunk, d.fileSource as fileSource
                """
        param = {"file_name" : file_name}
        return self.execute_query(query, param)`

**Comment by jexp** [comment]
We override documents with the same file-name intentionally.
So that you can re-upload documents.
