### ISSUE TITLE
how to use llm-graph-builder as an api

### ISSUE THREAD

**Issue by seshubonam** [neo4j-labs/llm-graph-builder#545]
https://neo4j.com/labs/genai-ecosystem/llm-graph-builder/

the ui is cool, and to use this as a tool in agent frameworks, im trying to find a way to use it as an api. 

to have all the functionality of the https://llm-graph-builder.neo4jlabs.com, as an api

any help? thanks!

**Comment by ais-qianhao-liu** [comment]
You can host the backend your self and all availabel api endpoints are in this file https://github.com/neo4j-labs/llm-graph-builder/blob/main/backend/score.py

**Comment by seshubonam** [comment]
also do you have an idea whats the difference between using llm-graph-builder vs the graphRAG accelerator from microsoft for graphRAG (https://github.com/Azure-Samples/graphrag-accelerator)

I prefer neo4j for making use of graph databases extensively in my project on top of the graphRAG. so its an easy choice for me if both are essentially providing the similar graph powered RAG feature for llms. 

its hard to find at which layer neo4j adds value to end user when i.plementing graphRAG following the microsoft method. 

if you can shed some light, will be helpful. thanks!

**Comment by ais-qianhao-liu** [comment]
Sorry I am not familiar with MS graphRAG accelerator, but as far as I know you can do some extra analysis with Neo4j GDS library and also it looks like you probably have to use MS Azure cloud with MS graphRAG accelerator together.

**Comment by jayanth-002** [comment]
@seshubonam, for more details about integrating GraphRAG with NEo4j, pls refer to the blog: https://neo4j.com/developer-blog/microsoft-graphrag-neo4j/

**Comment by seshubonam** [comment]
thanks

**Comment by kartikpersistent** [comment]
Hi @seshubonam if you are satisfied with the answer please close the issue
