### ISSUE TITLE
Need to handle empty string/tokens

### ISSUE THREAD

**Issue by karanchellani** [neo4j-labs/llm-graph-builder#563]
"{code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `apoc.merge.node`: Caused by: org.neo4j.internal.kernel.api.exceptions.schema.IllegalTokenNameException: '' is not a valid token name. Token names cannot be empty or contain any null-bytes.}"

**Comment by s3dhanth** [comment]
have you got any sollution for this?
