### ISSUE TITLE
please change `install==1.3.5` to `pip-install==1.3.5` in backend/requirements.txt

### ISSUE THREAD

**Issue by hao7Chen** [neo4j-labs/llm-graph-builder#567]
package `install` is not found. 

> Reference: https://github.com/eugenekolo/pip-install/issues/4 
                      https://pypi.org/project/pip-install/

**Comment by nargetdev** [comment]
Can confirm I experienced this as well.  On both Darwin and Arch

**Comment by jonojason** [comment]
This update also worked for our backend as we were wondering why the pipeline was breaking.

**Comment by ciroque** [comment]
This allowed me to build on Debian 6

**Comment by jtele2** [comment]
Also noticed this. Please updated. Thanks!

**Comment by leunglong0123** [comment]
thanks for that!

**Comment by timothylam1228** [comment]
Same problem

**Comment by kartikpersistent** [comment]
Hi @timothylam1228 Are facing same problem again?

**Comment by kartikpersistent** [comment]
The Fix is Pushed to DEV branch so check that

**Comment by timothylam1228** [comment]
It works now, sorry didn't notice that you have done the changes

Thanks you so much 🙏

**Comment by TQtong** [comment]
It's work for me, Thank you
