### ISSUE TITLE
How do I talk to existing graph data instead of starting from an imported file or link?

### ISSUE THREAD

**Issue by hao7Chen** [neo4j-labs/llm-graph-builder#570]
My local neo4j database already has a graph data, how do I talk to my existing data? Just like the integration case given by langchain.

**Comment by jexp** [comment]
in local deployment / DEV you can use "graph" search

You need a clean schema though, that's why it's not enabled in the publicly deployed version.

<img width="1289" alt="Bildschirmfoto 2024-07-21 um 14 31 58" src="https://github.com/user-attachments/assets/dd3a12c6-de5d-435c-b49d-82754fc42378">

**Comment by jexp** [comment]
Otherwise you'd have to add the structural elements that the app requires to make it work, e.g. Document node with fileName and status and Chunk nodes with text and embedding and vector index and connect your entities to the chunks.
