### ISSUE TITLE
Remove non-existent package 'install' from requirements.txt

### ISSUE THREAD

**Issue by guerinjeanmarc** [neo4j-labs/llm-graph-builder#573]
in backend, requirements.txt contains a package named 'install==1.3.5' which does not exist in the Python Package Index (PyPI).

Installing the app locally using docker or running the Backend separately gives an error while pip install -r requirements.txt because of this package

Solution:
Removing the line containing 'install==1.3.5' from the `requirements.txt` file resolves the issue and allows the application to install its dependencies successfully.

Proposed fix:
Remove the following line from `requirements.txt`:
install==1.3.5

**Comment by karanchellani** [comment]
@guerinjeanmarc thanks for suggestion, we have removed package install from requirements.txt

**Comment by jackwangzhifeng** [comment]
in backend, requirements.txt contains a package named 'aiohttp==3.9.3' which does not exist in the Python Package Index (PyPI).
the version is not exists! 
Proposed fix:
update the following line from requirements.txt:
aiohttp

**Comment by jexp** [comment]
@karanchellani please check

https://pypi.org/project/aiohttp/ 3.9.5 is the version there

**Comment by ShadowOnYOU** [comment]
I have deleted a total of three packages: install==1.3.5, safetensors==0.4.1, and scipy==1.10.1. Currently, the local front-end and back-end approach has not been affected.

**Comment by kartikpersistent** [comment]
@praveshkumar1988
