### ISSUE TITLE
possible to change openai model to gpt-4o-mini in the config for docker? 

### ISSUE THREAD

**Issue by seshubonam** [neo4j-labs/llm-graph-builder#599]
gpt-4o-mini significantly reduces the cost of graphRAG generation and more people.can experiment and compare outcomes with standard RAG with a similar model. 

is it possible to change the config to the newly released gpt-4o-mini or.does this need a PR?

**Comment by kartikpersistent** [comment]
Hi @seshubonam it's been added in the llm options you will be able to see that in dev version very soon
