### ISSUE TITLE
Front-end pass neo4j connection information to backend

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#6]
If there is a separate connection information provided in the front-end it should pass that to the backend in a suitable way when making requests.

e.g. for processing files the connection information of the front-end (if available) should be passed on as an extra nested payload and be used in the processing.

Same for listing sources for the table, it should use the front-end connection information.

If the backend is configured with a neo4j connection but the front-end is not connected, it should still work, then automatically using the backends connection config inside the backend.

**Comment by kartikpersistent** [comment]
It is new requirement we will discuss with backend team and make sure that even though the frontend is not connected with neo4j then also user should be able to upload files along with the file we will pass the connection values from the UI so that connection will be established from backend.

**Comment by kartikpersistent** [comment]
@jexp  As we discussed over the [slack](https://neo4j.slack.com/archives/C06CFDES6PR/p1706193517309539?thread_ts=1706191161.665629&cid=C06CFDES6PR) made the changes accordingly.
![Screenshot (896)](https://github.com/neo4j-labs/llm-graph-builder/assets/101251502/dfea7303-bc79-41c4-97bb-2901831d0afd)

**Comment by jexp** [comment]
Yep, looks ok, not sture if/how we need to encrypt it at some point, but for now it's ok.

**Comment by kartikpersistent** [comment]
ok
