### ISSUE TITLE
Want to keep my PDF data Private

### ISSUE THREAD

**Issue by Naveen-Chaurasia** [neo4j-labs/llm-graph-builder#600]
I am using the LLM Graph Builder application and have concerns regarding the privacy and security of the data I upload. Specifically, I need to ensure that the uploaded data (e.g., PDFs) remains private and is not accessible by unauthorized parties, including OpenAI. I would like to know the following:

**Privacy of Uploaded Data:**

1. How is the uploaded data stored within the application?
2. Are there any measures in place to ensure that the data remains private and secure?
3. Will OpenAI have access to the data that I upload to the LLM Graph Builder application?

**Comment by Kain-90** [comment]
At the moment, it seems to me that the process of handling data looks like this
1. Upload: the full uploaded files are temporarily stored in the `backend/merged_files` directory, and then stored in the neo4j database.
2. embedding session: the documents are divided into chunks, which are transformed into high level vectors by the embedding model and also stored in the neo4j database.
3. entity extraction session: each chunk is again extracted by the big model to extract entities and relationships from it, and finally stored to the neo4j database.

Therefore, if you want to ensure complete data privacy, you need to make sure that the data processor is local to you or a third party you trust.
1. neo4j database deployment
2. embedding model deployment
3. entity-relationship extraction llm deployment

If there is something missing, please feel free to add it.
