### ISSUE TITLE
Typo in GenericSourceModal.tsx

### ISSUE THREAD

**Issue by erikbijl** [neo4j-labs/llm-graph-builder#602]
Good afternoon,

There is a typo in a message for uploading web sources. Instead of `Knowledge Graph` it says `Knoweldge graph`. I tried to push the required change only I got a permission denied error to the repository. The change should me made on line 41 in: [GenericSourceModal.tsx](https://github.com/neo4j-labs/llm-graph-builder/blob/main/frontend/src/components/WebSources/GenericSourceModal.tsx)

**Comment by kartikpersistent** [comment]
Fixed
