### ISSUE TITLE
Webpage not working after upload

### ISSUE THREAD

**Issue by erikbijl** [neo4j-labs/llm-graph-builder#604]
Good morning, 

I was uploading an url as a web source that was not extracted due to probably due to some webpage protection. 
I uploaded the URL below as a web source. To verify this I checked the web-url and that one is indeed pointing to the url that I pasted. The odd thing there was that the filename had the name '"Just a moment..." instead of the article name (print screen 1). When I pressed 'generate graph' everything seems to be okay still. The problem became really clear when looking into the graph. There the only chunk that is generated has the following text: "Just a moment...Enable JavaScript and cookies to continue" (print screen 2). It seems that we cannot read the this URL correctly. Would be better if we provide some feedback when this is the case. Now you expect it to be working. 

[URL that I used](https://www.allianz.com/en/press/news/commitment/sponsorship/240612-allianz-welcomes-fc-bayern-footballer-harry-kane-as-global-allianz-brand-ambassador.html)

![Screenshot 2024-07-22 at 15 57 12](https://github.com/user-attachments/assets/55f899df-d0f0-4c50-9efd-3ecf0d139c9e)
![Screenshot 2024-07-23 at 08 55 56](https://github.com/user-attachments/assets/4137f9e3-aa1f-4179-ac54-d4b73b881be7)

**Comment by kartikpersistent** [comment]
@aashipandya will be better person to look at this web URL

**Comment by karanchellani** [comment]
@erikbijl I guess this is because when we hit this URL, first thing that we have to do is to 'Accept Cookies' and i guess this is the reason why actual content of article doesn't get extracted. We will debug this further and see if we can fix this. Thanks for pointing it out.
