### ISSUE TITLE
Regarding the issue of EMBEDDINGYMODEL having dimensions of 768 and 1024

### ISSUE THREAD

**Issue by gy850222** [neo4j-labs/llm-graph-builder#609]
I tried using EMBEDDIND_MODEL for other models and found that both models with dimensions of 768 and 1024 had issues.
For example:
model_name="intfloat/multilingual-e5-base", cache_folder="/embedding_model" dimension = 768
model_name="intfloat/multilingual-e5-large-instruct", cache_folder="/embedding_model" dimension = 1024

**.env:**
#EMBEDDING_MODEL = "distiluse-base-multilingual-cased-v2"
#EMBEDDING_MODEL = "intfloat/multilingual-e5-small"
#EMBEDDING_MODEL = "intfloat/multilingual-e5-large-instruct"
EMBEDDING_MODEL = "intfloat/multilingual-e5-base"

**common_fn.py:**

 embeddings = SentenceTransformerEmbeddings(
            #model_name="all-MiniLM-L6-v2"#, cache_folder="/embedding_model"
            #model_name="paraphrase-multilingual-MiniLM-L12-v2", cache_folder="/embedding_model"
            #model_name="distiluse-base-multilingual-cased-v2", cache_folder="/embedding_model"
            #model_name="intfloat/multilingual-e5-small", cache_folder="/embedding_model"
            #model_name="intfloat/multilingual-e5-large-instruct", cache_folder="/embedding_model"
            model_name="intfloat/multilingual-e5-base", cache_folder="/embedding_model"
            
        )
        #dimension = 384
        dimension = 768
        #dimension = 512
        #dimension = 1024
        logging.info(f"Embedding: Using SentenceTransformer , Dimension:{dimension}")

**Currently, only dimensions of 384 are available For example: EMBEDDING_MODEL = "intfloat/multilingual-e5-small"**

**log:**
Exception in post_processing tasks: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `db.index.vector.queryNodes`: Caused by: java.lang.IllegalArgumentException: Index query vector has 768 dimensions, but indexed vectors have 384.}
@jexp

**Comment by praveshkumar1988** [comment]
@gy850222 You need to drop existing vector index which have dimension 384. Please RUN Command `drop index vector`

**Comment by gy850222** [comment]
@praveshkumar1988 Thank you for your reminder. I have successfully achieved it. Thank you.:)
