### ISSUE TITLE
Typescript error when running docker-compose up --build

### ISSUE THREAD

**Issue by workprinond** [neo4j-labs/llm-graph-builder#614]
I am encountering the following error when running "docker-compose up --build", can you please give an insight why so?

 `11.44 src/components/QuickStarter.tsx(44,15): error TS2322: Type '{ openSettingsDialog: () => void; isSettingPanelExpanded: boolean; closeSettingModal: () => void; closeOrphanNodeDeletionModal: () => void; showOrphanNodeDeletionModal: boolean; openOrphanNodeDeletionModal: () => void; }' is not assignable to type 'IntrinsicAttributes & { isSettingPanelExpanded: boolean; closeSettingModal: () => void; openSettingsDialog: () => void; }'.
11.44   Property 'closeOrphanNodeDeletionModal' does not exist on type 'IntrinsicAttributes & { isSettingPanelExpanded: boolean; closeSettingModal: () => void; openSettingsDialog: () => void; }'.
11.44 src/utils/Utils.ts(190,92): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
11.44   Type 'undefined' is not assignable to type 'string'.
11.44 src/utils/Utils.ts(205,14): error TS2339: Property 'labels' does not exist on type 'Node'.
11.44 src/utils/Utils.ts(205,52): error TS2339: Property 'labels' does not exist on type 'Node'.
11.44 src/utils/Utils.ts(205,89): error TS2339: Property 'labels' does not exist on type 'Node'.
11.44 src/utils/Utils.ts(209,92): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
11.44   Type 'undefined' is not assignable to type 'string'.
11.44 src/utils/Utils.ts(217,68): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
11.44   Type 'undefined' is not assignable to type 'string'.
11.54 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11.54 error Command failed with exit code 2.`

**Comment by kartikpersistent** [comment]
Hi @workprinond  please use the DEV branch for local testing all type errors are fixed and we will merge to main very soon

**Comment by elheremes** [comment]
I'm using DEV branch and still getting this error.

`17.22 yarn run v1.22.22
17.27 $ tsc && vite build
24.13 src/utils/Utils.ts(190,92): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
24.13   Type 'undefined' is not assignable to type 'string'.
24.13 src/utils/Utils.ts(205,14): error TS2339: Property 'labels' does not exist on type 'Node'.
24.13 src/utils/Utils.ts(205,52): error TS2339: Property 'labels' does not exist on type 'Node'.
24.13 src/utils/Utils.ts(205,89): error TS2339: Property 'labels' does not exist on type 'Node'.
24.13 src/utils/Utils.ts(209,92): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
24.13   Type 'undefined' is not assignable to type 'string'.
24.13 src/utils/Utils.ts(217,68): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
24.13   Type 'undefined' is not assignable to type 'string'.
24.17 error Command failed with exit code 2.
24.17 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

![image](https://github.com/user-attachments/assets/b668fadf-7e63-4d18-8202-d4182a0131a7)
