### ISSUE TITLE
something wrong?

### ISSUE THREAD

**Issue by CarolVim** [neo4j-labs/llm-graph-builder#619]
<img width="1439" alt="截屏2024-07-28 晚上7 51 41" src="https://github.com/user-attachments/assets/24e7fbd6-e371-4a0e-bcd5-124c0180a312">

**Comment by CarolVim** [comment]
<img width="927" alt="截屏2024-07-28 晚上7 52 30" src="https://github.com/user-attachments/assets/0ae91a80-22b1-4ca3-ae14-834cdc98fffd">

**Comment by kartikpersistent** [comment]
Hi @CarolVim can you please elaborate the error which you got in the frontend.

**Comment by avbdasf** [comment]
I am having the same issue and I get the following warning when running the frontend:
`warn - The safelist pattern `/^(hover:)?n-text-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes

warn - The safelist pattern `/^(hover:)?n-bg-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes

warn - The safelist pattern `/^(active:)?n-bg-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes

warn - The safelist pattern `/^(hover:)?n-border-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes`

This occurs on both the main and dev branches.

**Comment by kartikpersistent** [comment]
Hi @avbdasf it is a warning it doesn't affect the application we will fix it soon

**Comment by avbdasf** [comment]
I am still only seeing the ErrorBoundary component when trying to run the frontend. 
![Screenshot 2024-08-05 at 11 25 34 PM](https://github.com/user-attachments/assets/9d1c5c6d-2805-4166-9eca-2d1960a95b76)
My node version is v20.16.0. Could you suggest how to fix this error?

**Comment by kartikpersistent** [comment]
Hi @avbdasf can you inspect the page and send us the Error log which you got in the console?

**Comment by kartikpersistent** [comment]
Hi @avbdasf share the logs asap

**Comment by aiyyyyyyy** [comment]
[]
index-19d9fe32.js:40  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at kA (index-19d9fe32.js:40:26100)
    at l0 (index-19d9fe32.js:40:27391)
    at jA (index-19d9fe32.js:40:30592)
    at l0 (index-19d9fe32.js:40:27541)
    at jA (index-19d9fe32.js:40:27851)
    at l0 (index-19d9fe32.js:40:27541)
    at jA (index-19d9fe32.js:40:27654)
    at l0 (index-19d9fe32.js:40:27541)
    at jA (index-19d9fe32.js:40:27654)
    at l0 (index-19d9fe32.js:40:27541)
i8 @ index-19d9fe32.js:40
a.componentDidCatch.n.callback @ index-19d9fe32.js:40
PR @ index-19d9fe32.js:38
JR @ index-19d9fe32.js:40
NA @ index-19d9fe32.js:40
TV @ index-19d9fe32.js:40
zV @ index-19d9fe32.js:40
Ip @ index-19d9fe32.js:40
tC @ index-19d9fe32.js:40
Z5 @ index-19d9fe32.js:38
zV @ index-19d9fe32.js:40
Ip @ index-19d9fe32.js:40
_A @ index-19d9fe32.js:40
H @ index-19d9fe32.js:25
fe @ index-19d9fe32.js:25
index-19d9fe32.js:1367 {error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of …}
index-19d9fe32.js:1367 {errorInfo: {…}}
index-19d9fe32.js:40  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at kA (index-19d9fe32.js:40:26100)
    at l0 (index-19d9fe32.js:40:27391)
    at jA (index-19d9fe32.js:40:30592)
    at l0 (index-19d9fe32.js:40:27541)
    at jA (index-19d9fe32.js:40:27851)
    at l0 (index-19d9fe32.js:40:27541)
    at jA (index-19d9fe32.js:40:27654)
    at l0 (index-19d9fe32.js:40:27541)
    at jA (index-19d9fe32.js:40:27654)
    at l0 (index-19d9fe32.js:40:27541)
i8 @ index-19d9fe32.js:40
a.componentDidCatch.n.callback @ index-19d9fe32.js:40
PR @ index-19d9fe32.js:38
JR @ index-19d9fe32.js:40
NA @ index-19d9fe32.js:40
TV @ index-19d9fe32.js:40
zV @ index-19d9fe32.js:40
Ip @ index-19d9fe32.js:40
tC @ index-19d9fe32.js:40
Z5 @ index-19d9fe32.js:38
zV @ index-19d9fe32.js:40
Ip @ index-19d9fe32.js:40
_A @ index-19d9fe32.js:40
H @ index-19d9fe32.js:25
fe @ index-19d9fe32.js:25
index-19d9fe32.js:1367 {error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of …}
index-19d9fe32.js:1367 {errorInfo: {…}}
llm-graph-builder.neo4jlabs.com/:1  Access to XMLHttpRequest at 'https://prodprocessing-backend-dcavk67s4a-uc.a.run.app/extract' from origin 'https://llm-graph-builder.neo4jlabs.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
index-19d9fe32.js:313 API Error: Dr {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
index-19d9fe32.js:1367  Axios error occurred: Network Error
jn @ index-19d9fe32.js:1367
await in jn
On @ index-19d9fe32.js:1367
Ne @ index-19d9fe32.js:1367
$t @ index-19d9fe32.js:1367
jo @ index-19d9fe32.js:1367
(匿名) @ index-19d9fe32.js:99
o.<computed> @ index-19d9fe32.js:99
F @ index-19d9fe32.js:96
aB @ index-19d9fe32.js:37
sB @ index-19d9fe32.js:37
lB @ index-19d9fe32.js:37
RR @ index-19d9fe32.js:37
PI @ index-19d9fe32.js:37
(匿名) @ index-19d9fe32.js:37
SS @ index-19d9fe32.js:40
iI @ index-19d9fe32.js:37
n6 @ index-19d9fe32.js:37
Y9 @ index-19d9fe32.js:37
OB @ index-19d9fe32.js:37
index-19d9fe32.js:155 
        
        
        POST https://prodprocessing-backend-dcavk67s4a-uc.a.run.app/extract net::ERR_FAILED 500 (Internal Server Error)
(匿名) @ index-19d9fe32.js:155
xhr @ index-19d9fe32.js:155
Cj @ index-19d9fe32.js:157
_request @ index-19d9fe32.js:158
request @ index-19d9fe32.js:157
(匿名) @ index-19d9fe32.js:153
RD @ index-19d9fe32.js:313
nFe @ index-19d9fe32.js:313
jn @ index-19d9fe32.js:1367
On @ index-19d9fe32.js:1367
Ne @ index-19d9fe32.js:1367
$t @ index-19d9fe32.js:1367
jo @ index-19d9fe32.js:1367
(匿名) @ index-19d9fe32.js:99
o.<computed> @ index-19d9fe32.js:99
F @ index-19d9fe32.js:96
aB @ index-19d9fe32.js:37
sB @ index-19d9fe32.js:37
lB @ index-19d9fe32.js:37
RR @ index-19d9fe32.js:37
PI @ index-19d9fe32.js:37
(匿名) @ index-19d9fe32.js:37
SS @ index-19d9fe32.js:40
iI @ index-19d9fe32.js:37
n6 @ index-19d9fe32.js:37
Y9 @ index-19d9fe32.js:37
OB @ index-19d9fe32.js:37

**Comment by aiyyyyyyy** [comment]
I am having the same issue

**Comment by kartikpersistent** [comment]
are you guys using latest DEV branch and env variables?

**Comment by jexp** [comment]
ping? otherwise will close

**Comment by surafelmuluye** [comment]
@CarolVim any solutions ?
