### ISSUE TITLE
"Vector index not found" when trying to connect

### ISSUE THREAD

**Issue by JoeyWangTW** [neo4j-labs/llm-graph-builder#625]
I'm seeing this error message showing up when trying to connect to a instance.
<img width="615" alt="Screenshot 2024-07-30 at 12 26 24 PM" src="https://github.com/user-attachments/assets/d3e332b3-dc2d-4c5d-bdf2-db60de139019">
I'm connecting with an empty database, do I need to do any setup before trying to connect?

**Comment by dtdannen** [comment]
Getting the same problem too, using the free empty aura instance

**Comment by dtdannen** [comment]
Looks like in line 70 of make_relationships.py might be where it's created.... 

```
graph.query("""CREATE VECTOR INDEX `vector` if not exists for (c:Chunk) on (c.embedding)
                            OPTIONS {indexConfig: {
                            `vector.dimensions`: $dimensions,
                            `vector.similarity_function`: 'cosine'
                            }}
                        """,
                        {
                            "dimensions" : dimension
                        }
                        )
```

**Comment by dtdannen** [comment]
Logs seem to indicate number of dimensions is 384: 
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/78db550d-f4f7-4aa3-b9d9-a28013c0b4e3">

**Comment by dtdannen** [comment]
I think I fixed it, go to your aura instance and run this query directly in it:

```
CREATE VECTOR INDEX `vector` if not exists for (c:Chunk) on (c.embedding)
                            OPTIONS {indexConfig: {
                            `vector.dimensions`: 384,
                            `vector.similarity_function`: 'cosine'
                            }}                        
```

So it should look like:

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/034a3377-69b5-44dc-be92-41e840f6aa8e">

**Comment by JoeyWangTW** [comment]
> Logs seem to indicate number of dimensions is 384: <img alt="image" width="1143" src="https://private-user-images.githubusercontent.com/590551/353599348-78db550d-f4f7-4aa3-b9d9-a28013c0b4e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNzM5NjEsIm5iZiI6MTcyMjM3MzY2MSwicGF0aCI6Ii81OTA1NTEvMzUzNTk5MzQ4LTc4ZGI1NTBkLWY0ZjctNGFhMy1iOWQ5LWEyODAxM2MwYjRlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQyMTA3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Njk2NmYyZTgxMWUwOTdiMjgzM2MwNWI2YWZhMGUzNTNkYmY3MWYyYTNhYWI1MTJmNTBkYjk5NzNmNjA5ZDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9gEAFL6z2LgzgJ7sNAGmw4KHM71x3oQuadeBCbhw0c0">

This worked, thanks!

**Comment by kartikpersistent** [comment]
Hi @JoeyWangTW vector index with supported dimension will be created on clicking create vector index button

**Comment by marcofiocco** [comment]
I clicked Create Vector Index button, but it got stuck forever, I had ot use
```
CREATE VECTOR INDEX `vector` if not exists for (c:Chunk) on (c.embedding)
                            OPTIONS {indexConfig: {
                            `vector.dimensions`: 384,
                            `vector.similarity_function`: 'cosine'
                            }}  
```
and then it connected.

**Comment by kartikpersistent** [comment]
sometimes API takes takes
