### ISSUE TITLE
Neo.TransientError.Transaction.DeadlockDetected

### ISSUE THREAD

**Issue by dhirajnair** [neo4j-labs/llm-graph-builder#629]
I get below deadlock error when uploading multiple files or trying to generate graph for multiple files. Please advise

`Traceback (most recent call last):
  File "/Users/dhirajnair/Documents/Projects/code/xx/llm-graph-builder/backend/score.py", line 163, in extract_knowledge_graph_from_file
    result = await asyncio.to_thread(
  File "/Users/dhirajnair/miniconda3/envs/rag10/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
 .....
neo4j.exceptions.TransientError: {code: Neo.TransientError.Transaction.DeadlockDetected} {message: ForsetiClient[transactionId=11273, clientId=33] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=11276, clientId=35]} on NODE(505) because holders of that lock are waiting for ForsetiClient[transactionId=11273, clientId=33].`

**Comment by kartikpersistent** [comment]
Hi @dhirajnair this happens when backend tries to write same node concurrently with multiple workers backend.

**Comment by dhirajnair** [comment]
shouldnt there be some locking mechanism or retry-with-timeout? Do we have to handle this in code ourselves? @kartikpersistent

**Comment by kartikpersistent** [comment]
Yes it must be handled in the code I guess. @aashipandya and @praveshkumar1988 have the better idea

**Comment by kartikpersistent** [comment]
we already created issue [link](https://github.com/neo4j-labs/llm-graph-builder/issues/554)
