### ISSUE TITLE
'str' object has no attribute 'content'

### ISSUE THREAD

**Issue by lemencolo** [neo4j-labs/llm-graph-builder#691]
After pouring the document in, the program quickly splits the document into blocks, but reports an error saying 'content has no attributes'.
<img width="1057" alt="Snipaste_2024-08-14_10-50-24" src="https://github.com/user-attachments/assets/3c6e935b-bcdc-46e7-8e1c-47df9fd4739b">

**Comment by lemencolo** [comment]
I don't quite understand how to correct this error.
![Uploading Snipaste_2024-08-14_10-52-13.png…]()

**Comment by praveshkumar1988** [comment]
@lemencolo I think, you are getting this error locally. So, can you please share the logs of this error to debug more.

**Comment by praveshkumar1988** [comment]
@lemencolo I think, you are getting this error locally. So, can you please share the logs of this error to debug more.

**Comment by jexp** [comment]
@lemencolo ping
