### ISSUE TITLE
Manually calling gc.collect is not recommended

### ISSUE THREAD

**Issue by Kain-90** [neo4j-labs/llm-graph-builder#692]
Referring to the link below, I learned that and previously had never manually called `gc.collect()` in Python code before.

https://stackoverflow.com/questions/26761784/where-to-call-gc-collect

**Comment by praveshkumar1988** [comment]
In some case like long-running processes that handle large amounts of data, memory might not be freed quickly enough, leading to memory bloat. So need to manually calling `gc.collect()`  that can help manage memory more proactively.
