### ISSUE TITLE
front-end-backend communication

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#7]
There seems to be a CORS issue. 

-> ok seems to be related to the GH codespaces, need to make the backend URL public to make it work for the time being, should be resolved when running it with docker or deploying it elsewhere.

But also connecting to a wrong back-end? Not sure if you hard-coded it, but it should just connect to localhost:8000 on the machine where the backend-is running or the configured base-URL.

Seems you have that hard-coded

https://github.com/neo4j-labs/llm-graph-builder/blob/main/frontend/src/components/DropZone.tsx#L10

1. it should not be hard-coded but come from an .env file (also provide an example.env)
2. it should not just hidden inside a UI component but a proper backend/REST API component !!
3. there should be a health check that valdiates that the backend is correctly running and indicate that to the user!

```
https://github.com/neo4j-labs/llm-graph-builder/issues/new
Access to XMLHttpRequest at 'https://animated-space-broccoli-jpgjg6pg59qcp7pg-8000.app.github.dev/predict' from origin 'https://studious-dollop-979pxr45x3p4p4-5173.app.github.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

POST https://animated-space-broccoli-jpgjg6pg59qcp7pg-8000.app.github.dev/predict net::ERR_FAILED 404 (Not Found)
```

my backend is running on: https://studious-dollop-979pxr45x3p4p4-8000.app.github.dev/docs

Later: Perhaps mid-term we can even serve them from the backend as static assets.

**Comment by prakriti-solankey** [comment]
Covered all three pointers. 
1. It should not just hidden inside a UI component but a proper backend/REST API component !!
  == Created separate utils and service js files to accommodate the distinction.
2. [New Requirement]  There should be a health check that validates that the backend is correctly running and indicate that to the user.
  == Connected/ Disconnected Tab is visible to validate backend is running or not.

Testing is in Progress
