### ISSUE TITLE
new feature: add the possibility to stop generating the graph

### ISSUE THREAD

**Issue by guerinjeanmarc** [neo4j-labs/llm-graph-builder#712]
I tried the llm-graph-builder on several large documents. I then realised that it was using a pre-defined schema that did not correspond to my documents.
I managed to delete the documents, but I could not stop the graph generation on the document already loaded, even if I disconnected the llm-graph-builder from the DB or if I deleted all nodes/relationships in my DB: the llm-graph-builder was still generating new nodes/relationship, for several minutes.

Proposed solution:
Having a button to stop the graph generation would save time and cost in case of mistakes, especially on large documents

**Comment by kartikpersistent** [comment]
Hi @guerinjeanmarc we already have a way to cancel the processing by click X button
![image](https://github.com/user-attachments/assets/c6391194-e2ed-4698-8af4-21838bf80b15)

**Comment by guerinjeanmarc** [comment]
My bad... 
thanks!!
