### ISSUE TITLE
chat bot can not work

### ISSUE THREAD

**Issue by edenbuaa** [neo4j-labs/llm-graph-builder#713]
I updated  files and generate graph successfully. and then talk in the chat, it response `I couldn't find any relevant documents to answer your question.`  no matter what I asked.

The detail info is:

`To generate this response, the process took 1.85 seconds, utilizing 0 tokens with the model llama3:8b in graph & vector mode.`

Did I miss anything?

**Comment by sakthii25** [comment]
`I couldn't find any relevant documents to answer your question` I also got this response.  because there are no relevant chunks for the given query above a certain threshold

**Comment by sakthii25** [comment]
> I updated files and generate graph successfully. and then talk in the chat, it response `I couldn't find any relevant documents to answer your question.` no matter what I asked.
> 
> The detail info is:
> 
> `To generate this response, the process took 1.85 seconds, utilizing 0 tokens with the model llama3:8b in graph & vector mode.`
> 
> Did I miss anything?

`I couldn't find any relevant documents to answer your question` I also got this response. because there are no relevant chunks for the given query above a certain threshold

**Comment by jexp** [comment]
@sakthii25 can your provide more details on your configuration, and if the graph extraction actually worked?
please share the backend logs.
