### ISSUE TITLE
Front-end startup failed

### ISSUE THREAD

**Issue by rookieR99** [neo4j-labs/llm-graph-builder#718]
I’m very sorry to bother you. After updating the front-end code, I encountered an error while viewing the webpage content. I'm not sure if it’s my issue.
![image](https://github.com/user-attachments/assets/0c4d5893-ff30-4844-a55b-f1cfc3ef1597)

**Comment by kartikpersistent** [comment]
Hi @rookieR99 can you share error you are getting in the inspect

**Comment by rookieR99** [comment]
Hi,This is the error message I see in the browser.
![image](https://github.com/user-attachments/assets/10419084-c205-4e61-9b66-9ea4ec1ba05c)

**Comment by kartikpersistent** [comment]
Have you followed valid ENV values

**Comment by rookieR99** [comment]
Which property in the ENV is related to this?

**Comment by kartikpersistent** [comment]
I am not able to see full error can you full inspect screen shot

**Comment by kartikpersistent** [comment]
I am sure you missed the ENV values in the frontend folder please read the readme before the setup

**Comment by rookieR99** [comment]
I created the frontend/.env file using copy/paste. The contents of the .env file are as follows:
![image](https://github.com/user-attachments/assets/9ba9495a-e08f-4d4c-84a0-e5317ca369de)

**Comment by rookieR99** [comment]
Oh~,I got the desired result. Thank you for your help!
