### ISSUE TITLE
VECTOR_GRAPH_SEARCH_QUERY  cypher ERROR

### ISSUE THREAD

**Issue by sakthii25** [neo4j-labs/llm-graph-builder#719]
while stimulate the chat setup in my local i got syntax error in the  `VECTOR_GRAPH_SEARCH_QUERY `

i got this error 
`ValueError: Cypher Statement is not valid
{code: Neo.ClientError.Statement.SyntaxError} {message: Importing WITH should consist only of simple references to outside variables. WHERE is not allowed. (line 25, column 9 (offset: 1242))
"        WITH e, similarity"
         ^}`

even i tried to run this cypher query in a standalone it also  gives the same syntax error.. Help me to resolve this query statement

**Comment by kartikpersistent** [comment]
@vasanthasaikalluri
