### ISSUE TITLE
Define the relationship before generating the KG

### ISSUE THREAD

**Issue by Howie-Arup** [neo4j-labs/llm-graph-builder#720]
Hi, I found that in the Key Features, we can provide our own custom schema to generate graph. But I didn't find it in the [LLM-graph builder tool](https://llm-graph-builder.neo4jlabs.com/. ) May I know where can I achieve this? My intention is to define the relationship before generating the KG so that the KG will be formed based on the pre-defined relationship. Thanks!

**Comment by kartikpersistent** [comment]
Hi @Howie-Arup you can set the custom schema in Entity Extraction Tab which we will get open on click Graph Enhancement button
![image](https://github.com/user-attachments/assets/788d5c62-476b-441b-b32f-2f4528be0449)

**Comment by kartikpersistent** [comment]
![image](https://github.com/user-attachments/assets/62ec7ef9-d65d-4604-9f21-2057c1641ddb)

**Comment by hliuci** [comment]
@kartikpersistent Got it. Thanks!

**Comment by Howie-Arup** [comment]
@kartikpersistent Got it. Thanks!
