### ISSUE TITLE
Modify the system prompt to generate the graph

### ISSUE THREAD

**Issue by hliuci** [neo4j-labs/llm-graph-builder#734]
Hi, I am using this [neo4j graph builder](https://llm-graph-builder.neo4jlabs.com/) to generate a graph. As the input has some industry-specific contexts, may I know is there a flexibility to modify the system prompt to generate the graph (either via the online tool or the github codes)? Thanks!

**Comment by kartikpersistent** [comment]
https://github.com/neo4j-labs/llm-graph-builder/issues/618

**Comment by kartikpersistent** [comment]
@aashipandya

**Comment by aashipandya** [comment]
Hi @hliuci 
If you are running application on local then there is an option to pass human prompt as parameter to LLMGraphTransformer in backend/src/llm,py file. 
From UI there is no option right now.

**Comment by hliuci** [comment]
Thanks! @kartikpersistent
