### ISSUE TITLE
Incorrect calculation of the number of relationships

### ISSUE THREAD

**Issue by xcd008** [neo4j-labs/llm-graph-builder#740]
After performing entity relation extraction on the document, the code calculated the number of relationships without deduplication and only counted the relationships for the last chunk.
![image](https://github.com/user-attachments/assets/cb6b2de3-f4f1-40d2-a814-34ed2733a545)

**Comment by xcd008** [comment]
reviewing the code, I found that the calculation of relationships was not within the loop that iterates over the graph_documents and was placed in a list object without deduplication.

**Comment by xcd008** [comment]
> After performing entity relation extraction on the document, the code calculated the number of relationships without deduplication and only counted the relationships for the last chunk. ![image](https://private-user-images.githubusercontent.com/21971609/365876269-cb6b2de3-f4f1-40d2-a814-34ed2733a545.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5Mzc1OTMsIm5iZiI6MTcyNTkzNzI5MywicGF0aCI6Ii8yMTk3MTYwOS8zNjU4NzYyNjktY2I2YjJkZTMtZjRmMS00MGQyLWE4MTQtMzRlZDI3MzNhNTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAzMDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTIxZmYzZDEzZjRhNjA4NjQ1NWU5M2QwMGYxMmIyNWE4YWY3ZDNkNzE3NTMxMTE2N2M3OTkzOGQzNTA2MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F4Xs4ot4e8T8IcFI-0K0NWIft7Qtlwpkasdov5E2bhQ)

reviewing the code, I found that the calculation of relationships was not within the loop that iterates over the graph_documents and was placed in a list object without deduplication.

**Comment by kartikpersistent** [comment]
@aashipandya

**Comment by kartikpersistent** [comment]
Hi, @xcd008 can you point out which code part you are mentioning it is fixed in DEV check it once

**Comment by xcd008** [comment]
> Hi, @xcd008 can you point out which code part you are mentioning it is fixed in DEV check it once
backend/src/main.py  Here, and it has not been resolved yet.
![image](https://github.com/user-attachments/assets/274927fc-7aea-41e3-bc6d-4383e43730ae)

**Comment by praveshkumar1988** [comment]
Hi @xcd008 As per the latest code, above code is in function name "processing_chunks" at Line 410 which is already iterates in For Loop at line no. 329. Also we are passing node count and relationship count as param in the function for adding total count of all chunks process extraction.
The reason behind to take duplication relationship because each relationship have source node and target node to make relation and similar relationship can have different source and target node.

I hope, this is enough to elaborate the functionality.

If you have still any question, please let me know.

**Comment by xcd008** [comment]
Thank you, I understand that relationships are not being de-duplicated, meaning they are not being counted by category; however, I have another question: why is the loop that iterates through relationships at line 437 not nested within the loop that iterates through graph_documents at line 429?
![image](https://github.com/user-attachments/assets/e62d4fac-1498-42cd-a34e-4df062410f5e)

**Comment by praveshkumar1988** [comment]
@xcd008 I think, It should be nested because we are getting relationship from graph_document. Will check and correct.
Thanks for pointing out.
