### ISSUE TITLE
Build failed with failed to solve: process "/bin/sh -c apt-get update

### ISSUE THREAD

**Issue by naveen-420** [neo4j-labs/llm-graph-builder#745]
I'm stuck on the docker compose command because of the blow errors after docker-compose up --build.

> > [llm-graph-builder-dev-backend 3/6] RUN apt-get update &&    apt-get install -y --no-install-recommends        libgl1-mesa-glx        libreoffice        cmake        poppler-utils        tesseract-ocr &&    apt-get clean &&    rm -rf /var/lib/apt/lists/*:
> #0 0.244 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
> #0 0.318 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
> #0 0.329 Err:1 http://deb.debian.org/debian bookworm InRelease
> #0 0.329   At least one invalid signature was encountered.
> #0 0.345 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
> #0 0.345   At least one invalid signature was encountered.
> #0 0.345 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
> #0 0.378 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
> #0 0.378   At least one invalid signature was encountered.
> #0 0.380 Reading package lists...
> #0 0.386 W: GPG error: http://deb.debian.org/debian bookworm InRelease: At least one invalid signature was encountered.
> #0 0.386 E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
> #0 0.386 W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: At least one invalid signature was encountered.
> #0 0.386 E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
> #0 0.386 W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: At least one invalid signature was encountered.
> #0 0.386 E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
> ------
> failed to solve: process "/bin/sh -c apt-get update &&    apt-get install -y --no-install-recommends        libgl1-mesa-glx        libreoffice        cmake        poppler-utils        tesseract-ocr &&    apt-get clean &&    rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by kartikpersistent** [comment]
@praveshkumar1988

**Comment by naveen-420** [comment]
Anyone else facing the issue ?. I tried with different branches, still facing the same issue. Looking for any suggestions or help. Thanks

**Comment by praveshkumar1988** [comment]
No error, Build successful and running application
![image](https://github.com/user-attachments/assets/30db7955-c64a-4141-aa3e-5613df1ced06)

**Comment by naveen-420** [comment]
@praveshkumar1988 Can you please let me, which version of docker  and llm-graph-builder  you are using. Thanks

**Comment by praveshkumar1988** [comment]
@naveen-420 
Docker version 26.1.4-1
langchain-experimental Version: 0.0.62

llm-graph-builder is part of langchain-experimental library.
Ran docker-compose command from DEV branch. I think all branch have same docker-compose.yml file

**Comment by naveen-420** [comment]
Closing as issue in my local docker
