### ISSUE TITLE
Embedding can not be changed to openai model with dimension 1536

### ISSUE THREAD

**Issue by paulvble** [neo4j-labs/llm-graph-builder#753]
Hello, I've noticed that data fed via the Graph Builder is only using the transformer embedding model with dimension 384  . However this creates a mismatch when I use an embedding model with 1536 dimension in the app. Is there a way to select the open embedding model from the GUI so that the data stored in the database equally holds the 1536 dimension? Please advice how to solve this. thanks.

**Comment by kartikpersistent** [comment]
@jexp

**Comment by maxgosk** [comment]
Hi, you cannot have multiple nodes on the same database with different dimensions, if you want to change to openai 1536 you have to reprocess your old chunks that has the 384 embedding

**Comment by jexp** [comment]
By default we use sentence transformer to stay independent of the cloud provider.
In priciniple if you deploy it yourself you can also choose otehr embedding models (vertex ai or openai)
We also have a version running on https://llm-graph-builder-openai.neo4jlabs.com/ that uses the openai 1536 embedding model.

**Comment by paulvble** [comment]
thanks @jexp. this works indeed. I saw the options in the source file, so I understand what you mean. Minor point on the provided application https://llm-graph-builder-openai.neo4jlabs.com/ ; a suggestion to also add the "advance" button so users can pre-define the nodes and relationships like the version with the sentence transformer.

**Comment by kartikpersistent** [comment]
It is already available in our application you can click on graph enhancement button where you can provide predefine schema
![image](https://github.com/user-attachments/assets/55fda130-e3b7-43c3-97b8-6236b0b238a1)

**Comment by kartikpersistent** [comment]
HI @paulvble we have not updated the openai version will do this
