### ISSUE TITLE
Front end Docker build issue

### ISSUE THREAD

**Issue by ankdadoo** [neo4j-labs/llm-graph-builder#778]
Downloaded the code . During docker compose command to build both backend and front end , am stuck on this front end build issue . any ideas what might be causing this error. checked the .env files for both backend and front end . and the error is not self explanatory 

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building frontend
[+] Building 15.6s (12/14)                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 37B                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 34B                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                                                                         0.7s
 => [internal] load metadata for docker.io/library/node:20                                                                                                                              0.7s
 => CACHED [stage-1 1/3] FROM docker.io/library/nginx:alpine@sha256:a5127daff3d6f4606be3100a252419bfa84fd6ee5cd74d0feaca1a5068f97dcf                                                    0.0s
 => [build 1/6] FROM docker.io/library/node:20@sha256:db5dd2f30cb82a8bdbd16acd4a8f3f2789f5b24f6ce43f98aa041be848c82e45                                                                  0.0s
 => [internal] load build context                                                                                                                                                       0.0s
 => => transferring context: 10.04kB                                                                                                                                                    0.0s
 => CACHED [build 2/6] WORKDIR /app                                                                                                                                                     0.0s
 => CACHED [build 3/6] COPY package.json yarn.lock ./                                                                                                                                   0.0s
 => CACHED [build 4/6] RUN yarn install                                                                                                                                                 0.0s
 => CACHED [build 5/6] COPY . ./                                                                                                                                                        0.0s
 => ERROR [build 6/6] RUN VITE_BACKEND_API_URL=http://localhost:8000     VITE_REACT_APP_SOURCES=local,youtube,wiki,s3     VITE_LLM_MODELS=diffbot,openai-gpt-3.5,openai-gpt-4o     VI  14.8s
------                                                                                                                                                                                       
 > [build 6/6] RUN VITE_BACKEND_API_URL=http://localhost:8000     VITE_REACT_APP_SOURCES=local,youtube,wiki,s3     VITE_LLM_MODELS=diffbot,openai-gpt-3.5,openai-gpt-4o     VITE_GOOGLE_CLIENT_ID=""     VITE_BLOOM_URL=https://workspace-preview.neo4j.io/workspace/explore?connectURL={CONNECT_URL&search=Show+me+a+graph&featureGenAISuggestions=true&featureGenAISuggestionsInternal=true}     VITE_CHUNK_SIZE=5242880     VITE_TIME_PER_PAGE=50     VITE_ENV=DEV     VITE_LARGE_FILE_SIZE=5242880     VITE_CHAT_MODES=""     VITE_BATCH_SIZE=2     yarn run build:                
#12 0.779 yarn run v1.22.22                                                                                                                                                                  
#12 0.871 $ tsc && vite build
#12 14.61 src/components/FileTable.tsx(38,10): error TS6133: 'ArrowPathIconSolid' is declared but its value is never read.
#12 14.61 src/components/FileTable.tsx(52,73): error TS6133: 'onRetry' is declared but its value is never read.
#12 14.71 error Command failed with exit code 2.
#12 14.71 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c VITE_BACKEND_API_URL=$VITE_BACKEND_API_URL     VITE_REACT_APP_SOURCES=$VITE_REACT_APP_SOURCES     VITE_LLM_MODELS=$VITE_LLM_MODELS     VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID     VITE_BLOOM_URL=$VITE_BLOOM_URL     VITE_CHUNK_SIZE=$VITE_CHUNK_SIZE     VITE_TIME_PER_PAGE=$VITE_TIME_PER_PAGE     VITE_ENV=$VITE_ENV     VITE_LARGE_FILE_SIZE=${VITE_LARGE_FILE_SIZE}     VITE_CHAT_MODES=$VITE_CHAT_MODES     VITE_BATCH_SIZE=$VITE_BATCH_SIZE     yarn run build]: exit code: 2
ERROR: Service 'frontend' failed to build : Build failed

**Comment by kartikpersistent** [comment]
It is fixed in DEV branch we will merge to main soon

**Comment by kartikpersistent** [comment]
Fixed

**Comment by ankdadoo** [comment]
Thanks Kartik for reviewing it . Should i just take a clone of latest code and the issue is merged or will be a later time . Please advise

**Comment by kartikpersistent** [comment]
Hi @ankdadoo you can take pull of main branch
