### ISSUE TITLE
can't build docker. read timed out

### ISSUE THREAD

**Issue by fridaystreet** [neo4j-labs/llm-graph-builder#785]
First time trying to use the library. running the docker compose command but getting the following read timeout. Couldn't find any othe rreported issues with it. I read through a few other issues that might possibly be related, some seem oto suggest using dev branch. tried this aswell but still broken.

I'm guessing maybe it's a problem with the repo? but should there be a probelm?

Any assistance would be greatly appreciated

#10 56.24 Collecting torch>=1.12.1
#10 56.27   Downloading torch-2.4.1-cp310-cp310-manylinux2014_aarch64.whl (89.7 MB)
#10 78.52      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━           68.2/89.7 MB 3.7 MB/s eta 0:00:06
ERROR: Exception:
#9 147.6 Traceback (most recent call last):
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
#9 147.6     yield
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
#9 147.6     data = self._fp_read(amt) if not fp_closed else b""
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
#9 147.6     return self._fp.read(amt) if amt is not None else self._fp.read()
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
#9 147.6     data = self.__fp.read(amt)
#9 147.6   File "/usr/local/lib/python3.10/http/client.py", line 466, in read
#9 147.6     s = self.fp.read(amt)
#9 147.6   File "/usr/local/lib/python3.10/socket.py", line 717, in readinto
#9 147.6     return self._sock.recv_into(b)
#9 147.6   File "/usr/local/lib/python3.10/ssl.py", line 1307, in recv_into
#9 147.6     return self.read(nbytes, buffer)
#9 147.6   File "/usr/local/lib/python3.10/ssl.py", line 1163, in read
#9 147.6     return self._sslobj.read(len, buffer)
#9 147.6 TimeoutError: The read operation timed out
#9 147.6 
#9 147.6 During handling of the above exception, another exception occurred:
#9 147.6 
#9 147.6 Traceback (most recent call last):
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
#9 147.6     status = run_func(*args)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
#9 147.6     return func(self, options, args)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
#9 147.6     requirement_set = resolver.resolve(
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
#9 147.6     result = self._result = resolver.resolve(
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
#9 147.6     state = resolution.resolve(requirements, max_rounds=max_rounds)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
#9 147.6     failure_causes = self._attempt_to_pin_criterion(name)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
#9 147.6     criteria = self._get_updated_criteria(candidate)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
#9 147.6     self._add_to_criteria(criteria, requirement, parent=candidate)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
#9 147.6     if not criterion.candidates:
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
#9 147.6     return bool(self._sequence)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#9 147.6     return any(self)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#9 147.6     return (c for c in iterator if id(c) not in self._incompatible_ids)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#9 147.6     candidate = func()
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
#9 147.6     self._link_candidate_cache[link] = LinkCandidate(
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
#9 147.6     super().__init__(
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
#9 147.6     self.dist = self._prepare()
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
#9 147.6     dist = self._prepare_distribution()
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
#9 147.6     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
#9 147.6     return self._prepare_linked_requirement(req, parallel_builds)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
#9 147.6     local_file = unpack_url(
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
#9 147.6     file = get_http_url(
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
#9 147.6     from_path, content_type = download(link, temp_dir.path)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
#9 147.6     for chunk in chunks:
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
#9 147.6     for chunk in iterable:
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
#9 147.6     for chunk in response.raw.stream(
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
#9 147.6     data = self.read(amt=amt, decode_content=decode_content)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
#9 147.6     with self._error_catcher():
#9 147.6   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
#9 147.6     self.gen.throw(typ, value, traceback)
#9 147.6   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
#9 147.6     raise ReadTimeoutError(self._pool, None, "Read timed out.")
#9 147.6 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by fridaystreet** [comment]
Not sure if this helps but, looks like this commit caused an issue (ie last time requirements.txt was updated) https://github.com/neo4j-labs/llm-graph-builder/commit/292ae9e6cdb65653d1168d939d6159c88539358a

I've rolled back to this commit just before it and it's working ok https://github.com/neo4j-labs/llm-graph-builder/commit/3c2e3448598750e943b545f0947460a2658e7f2c

**Comment by praveshkumar1988** [comment]
@fridaystreet I don't think above change are affected the application code because I just create latest build using docker-compose up --build command. Its working fine also all the latest DEV changes deployed on GCP cloud run with working stage. [](https://dev-frontend-967196130891.us-central1.run.app/)
