### ISSUE TITLE
Configured diffbot but getting open_ai error

### ISSUE THREAD

**Issue by richdatasci** [neo4j-labs/llm-graph-builder#791]
I have configured my .env file to only use diffbot with the correct api key ie:

VITE_LLM_MODELS="diffbot"
DIFFBOT_API_KEY="somekey"

However when I prompt it gives the following error, it's still looking for open_ai llm: 

![image](https://github.com/user-attachments/assets/09d15595-ae47-4981-9ce0-72377aaa403e)

Has any one got a fix for this?

**Comment by karanchellani** [comment]
@richdatasci By default in chat we use Openai gpt4 as default chat model as diffbot does not support chat functionality

**Comment by richdatasci** [comment]
Got it!  Thanks!
