### ISSUE TITLE
Backend Use Only ChatBot not working

### ISSUE THREAD

**Issue by Stamenov** [neo4j-labs/llm-graph-builder#813]
Hi,

I have been using the https://llm-graph-builder.neo4jlabs.com/ to build a KG by connecting to a free Aura instance.
I have a bunch of nodes and relationships as can been seen in the Inspect Generated Graph on the llm-graph-builder webapp.

Now I would like to use the local backend setup from this repo, connecting to the Aura instance and send queries to backend which can communicate with the remote Aura instance (connection has been checked and works).

Using the **/chat_bot_chat_bot_post** in the fastapi /docs endpoint is causing me problems, while it works online::

```
{
  "status": "Success",
  "data": {
    "session_id": "XXXXX",
    "message": "Something went wrong",
    "info": {
      "sources": [],
      "chunkids": [],
      "error": "Exception :- An error occurred while retrieving the Neo4jVector index '{index_name}' or creating the retriever. Please drop and create a new vector index: {e}",
      "mode": "graph+vector+fulltext",
      "response_time": 1.91
    },
    "user": "chatbot"
  }
}
```

One parameter that was challenging was actually the session_id, which basically I have copied by inspecting the request payload on the webapp. As mentioned db credentials and connection there work.

Thanks in advance.

**Comment by Stamenov** [comment]
I have interpreted the session_id as a front-end-related id, possible it has to do with the db/index connection and thus it is the issue? 

Please help me understand how to use the chat bot API alternatively as an API?

**Comment by karanchellani** [comment]
Hi @Stamenov can you try dropping all vector indexes present in your DB and then try again.

**Comment by kartikpersistent** [comment]
Hi @Stamenov are you able to solve this issue?

**Comment by Stamenov** [comment]
I was able to solve the issue. Basically the code is not stable at all for user input - small changes to input like space between "+" and "vector" is not in any way sanitized,e.g.:
backend/src/QA_integration_new.py
if mode == "fulltext" or mode == "graph + vector + fulltext":

Not to mention undefined variables later on - "document_names" and small stuff like this.
