### ISSUE TITLE
Chat only URL

### ISSUE THREAD

**Issue by markNZed** [neo4j-labs/llm-graph-builder#818]
Great project, thanks. I would like to provide two UI, one that allows for uploading documents, exploring the graph etc. (this is the current UI), and a second UI that provides only the chat interface. I think this might be a nice way of demoing the advantages of neo4j and providing a standard chat interface. No doubt this could be hacked together very quickly but I thought I would ask for suggestions here and whether it makes sense to create a PR.

**Comment by jexp** [comment]
Yes we had this on our list of TODOs, could be somehing nice and quick for the next release the ability to pop out the chat interface and have it available on it's own URL.
@karanchellani can you capture that please.
