### ISSUE TITLE
Neo4j-desktop local db with Docker compose

### ISSUE THREAD

**Issue by paolo-tamagnini-tr** [neo4j-labs/llm-graph-builder#824]
Hi there,
I read [here](https://neo4j.com/labs/genai-ecosystem/llm-graph-builder-deployment/) that

> If want to use [Neo4j Desktop](https://neo4j.com/product/developer-tools/#desktop) instead, you need to configure your NEO4J_URI=bolt://host.docker.internal to allow the Docker container to access the network running on your computer.

is this up to date?

the readme states instead:

> If you are using Neo4j Desktop, you will not be able to use the docker-compose but will have to follow the [separate deployment of backend and frontend section](https://github.com/neo4j-labs/llm-graph-builder#running-backend-and-frontend-separately-dev-environment).

so which is it?

I tried the first one but i cannot get it to connect

neo4j desktop:

<img width="915" alt="Screenshot 2024-10-23 at 17 20 02" src="https://github.com/user-attachments/assets/729678f9-bfea-4fa3-a28b-c045cbd20861">

neo4j builder:
<img width="750" alt="Screenshot 2024-10-23 at 17 20 42" src="https://github.com/user-attachments/assets/88deee1d-c160-45aa-888c-fa804b807d42">

the root `.env` i edited before the docker command

```
# Mandatory
OPENAI_API_KEY=""
DIFFBOT_API_KEY=""

# Optional Backend
EMBEDDING_MODEL="all-MiniLM-L6-v2"
IS_EMBEDDING="true"
KNN_MIN_SCORE="0.94"
# Enable Gemini (default is False) | Can be False or True
GEMINI_ENABLED=False
# LLM_MODEL_CONFIG_ollama_llama3="llama3,http://host.docker.internal:11434"

# Enable Google Cloud logs (default is False) | Can be False or True
GCP_LOG_METRICS_ENABLED=False
NUMBER_OF_CHUNKS_TO_COMBINE=6
UPDATE_GRAPH_CHUNKS_PROCESSED=20
NEO4J_URI="bolt://host.docker.internal"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="password"
LANGCHAIN_API_KEY=""
LANGCHAIN_PROJECT=""
LANGCHAIN_TRACING_V2="true"
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
GCS_FILE_CACHE=False
ENTITY_EMBEDDING=True

# Optional Frontend
VITE_BACKEND_API_URL="http://localhost:8000"
VITE_BLOOM_URL="https://workspace-preview.neo4j.io/workspace/explore?connectURL={CONNECT_URL}&search=Show+me+a+graph&featureGenAISuggestions=true&featureGenAISuggestionsInternal=true"
VITE_REACT_APP_SOURCES="local"
VITE_LLM_MODELS="diffbot,openai-gpt-3.5,openai-gpt-4o" # ",ollama_llama3"
VITE_ENV="DEV"
VITE_TIME_PER_PAGE=50
VITE_CHUNK_SIZE=5242880
VITE_GOOGLE_CLIENT_ID=""
VITE_CHAT_MODES=""
VITE_BATCH_SIZE=2

LLM_MODEL_CONFIG_azure_ai_gpt_35="gpt-xxxxx,xxxx,xxxxxx,xxxxx"
LLM_MODEL_CONFIG_azure_ai_gpt_4o="gpt-xxxxx,xxxx,xxxxxx,xxxxx"
LLM_MODELS="azure_ai_gpt_35,azure_ai_gpt_4o"
```

**Comment by kartikpersistent** [comment]
Hi @paolo-tamagnini-tr have you mentioned that port on which neo4j was running in the NEO4j_URI or in frontend ?
You have to mention bolt://host.docker.internal:PORTNUMBER

**Comment by paolo-tamagnini-tr** [comment]
thanks, that worked, not sure if i missed something in the docs or whether it was not mentioned

I have another issue now, i cannot select an azure model from the dropdown:

<img width="566" alt="Screenshot 2024-10-28 at 12 10 17" src="https://github.com/user-attachments/assets/b4f29d2e-b091-407a-a253-19e140c26c7e">

those are the env_var i am trying at the moment

```
# Optional Frontend
VITE_BACKEND_API_URL="http://localhost:8000"
VITE_BLOOM_URL="https://workspace-preview.neo4j.io/workspace/explore?connectURL={CONNECT_URL}&search=Show+me+a+graph&featureGenAISuggestions=true&featureGenAISuggestionsInternal=true"
VITE_REACT_APP_SOURCES="local"
VITE_LLM_MODELS="azure_ai_gpt_35,azure_ai_gpt_4o" # ",ollama_llama3"
VITE_ENV="DEV"
VITE_TIME_PER_PAGE=50
VITE_CHUNK_SIZE=5242880
VITE_GOOGLE_CLIENT_ID=""
VITE_CHAT_MODES=""
VITE_BATCH_SIZE=2

LLM_MODEL_CONFIG_azure_ai_gpt_35="gpt-xxxxx,xxxx,xxxxxx,xxxxx"
LLM_MODEL_CONFIG_azure_ai_gpt_4o="gpt-xxxxx,xxxx,xxxxxx,xxxxx"
LLM_MODELS="azure_ai_gpt_35,azure_ai_gpt_4o"
```

can you spot anything that i am missing?

**Comment by kartikpersistent** [comment]
There is nothing wrong in the env We have changed the way of configuring the models you just need to put VITE_ENV="DEV" to try out all models please take the latest pull of main and refer to the readme for configuration

**Comment by paolo-tamagnini-tr** [comment]
the problem was not `VITE_ENV` but `VITE_LLM_MODELS_PROD`.
works now, thanks

**Comment by kartikpersistent** [comment]
Glad That It worked we changed readme for better clarity

**Comment by ZijinQiu** [comment]
Can I use a local existing database for QA when connecting to neo4j desktop?
