### ISSUE TITLE
Using Ollama llama3.1:8b  the UI never references entity nodes and HAS_ENTITY relationships created

### ISSUE THREAD

**Issue by michela** [neo4j-labs/llm-graph-builder#830]
Apologies in advance for duplicating issue - can't find the note that there are known Ollama issues:

My graph created using LLM set to Ollama llama3.1:8b creates looks correct - lots of entities but 

Clicking on View column in the results table gives

_No Nodes and Relations for the <source> file_

The KG does though contain nodes and HAS_ENTITY relationships.

The chatbot does work. In Retrieval information, Sources used is correct. But Top Entities used and Chunks are blank

**Comment by kartikpersistent** [comment]
which mode you used for chat?

**Comment by kartikpersistent** [comment]
Make sure that you should chat after post processing call for better/advanced retrieval

**Comment by jexp** [comment]
Hi Michela,
Can you please provide some screenshots from your graph and outputs from the processing? 
You can also copy the whole table row now into a json and download the chat as json as well for sharing.
And perhaps also the file that you used  for testing?
