### ISSUE TITLE
about  add member to allowed Nodes list  

### ISSUE THREAD

**Issue by Whhhzc** [neo4j-labs/llm-graph-builder#831]
Hello, I'd like to ask how I can add new members to allowNodes when using the local Ollama. I noticed that allowNodes only has a few labels in the code. I tried adding a new label in the Neo4j database, but when I checked through the code output, it couldn't be added to the allowNodes list. The same goes for allowRelations. Please help me with this. Thank you very much.  
This is my code output.It show that allowedNodes only this members 
![微信图片_20241025105741](https://github.com/user-attachments/assets/458b84f2-a7e6-4313-b9d5-5868b399f9bd)

**Comment by jexp** [comment]
This is just something you would add to the API call 
or if you use the underlying LangChain code you can pass in there as a parameter.
