### ISSUE TITLE
Something went wrong Sorry there was a problem loading this page Documentation

### ISSUE THREAD

**Issue by zzll22** [neo4j-labs/llm-graph-builder#858]

**Comment by kartikpersistent** [comment]
Hi @zzll22  can you share more info what exact error you are getting in the console and have you followed the documentation for running in it locally.

**Comment by NAMEs** [comment]
yarn run v1.22.19
$ vite --host 0.0.0.0

  VITE v4.5.3  ready in 238 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://10.222.96.64:5173/
  ➜  press h to show help

warn - The safelist pattern `/^(hover:)?n-text-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes

warn - The safelist pattern `/^(hover:)?n-bg-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes

warn - The safelist pattern `/^(active:)?n-bg-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes

warn - The safelist pattern `/^(hover:)?n-border-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes
