### ISSUE TITLE
Open AI Connection error 

### ISSUE THREAD

**Issue by abhishekkumar-27** [neo4j-labs/llm-graph-builder#865]
{
    "status": "Failed",
    "error": "Connection error.",
    "message": "Failed To Process File:einsteins-patents-inventions.pdf or LLM Unable To Parse Content Connection error.",
    "file_name": "einsteins-patents-inventions.pdf"
}
![Image](https://github.com/user-attachments/assets/55badaf0-bc34-4f46-a886-d5e91631174f)

**Comment by karanchellani** [comment]
Fixed
