### ISSUE TITLE
How to resolve the error when generating charts after the frontend uploads a PDF file?

### ISSUE THREAD

**Issue by miyuan12345** [neo4j-labs/llm-graph-builder#875]
I keep getting errors while generating charts, whether I pass a PDF file or a TXT file (attached image). Is there any way to solve this problem?
<img width="750" alt="8eca5424d307af559019a3185d352fe" src="https://github.com/user-attachments/assets/db8211f6-aae8-41de-b379-95fc69eb99a3">
<img width="745" alt="b065bde1de64b0a4538f96d29fb1fcc" src="https://github.com/user-attachments/assets/431b15de-75d1-48df-8d1b-c0ffb3bbdb51">

**Comment by karanchellani** [comment]
Hi @miyuan12345, can you share sample pdf or txt file you are trying to process, we will check why its failing.

**Comment by miyuan12345** [comment]
> 您好，您能否分享您尝试处理的示例 pdf 或 txt 文件，我们将检查其失败的原因。

好的好的，这是我的pdf和txt
[4.1.pdf](https://github.com/user-attachments/files/17774339/4.1.pdf)
[4.1.txt](https://github.com/user-attachments/files/17774340/4.1.txt)

**Comment by miyuan12345** [comment]
> Hi @miyuan12345, can you share sample pdf or txt file you are trying to process, we will check why its failing.

Okay, here are my PDF and TXT files:
[4.1.pdf](https://github.com/user-attachments/files/17789251/4.1.pdf)
[4.1.txt](https://github.com/user-attachments/files/17789252/4.1.txt)

**Comment by kartikpersistent** [comment]
![{81995696-51BD-41E0-A106-43E07C644ADA}](https://github.com/user-attachments/assets/541ad8ef-6556-4d24-b1fa-2255ab8cf503)
![{79EBB618-B785-4AE7-81CF-3D4043CC3511}](https://github.com/user-attachments/assets/5327f093-2e23-4671-b18c-6dd323b2bba5)
Hi @miyuan12345  it is working at our end can you try on deployed version also share which specific llm you choose for extraction

**Comment by miyuan12345** [comment]
I followed your video on Bilibili and didn't make any changes, so I'm not sure which specific LLM I chose for extraction. I also don't know where my code went wrong, but when deploying the environment and processing the requirements.txt file, I encountered many errors. I'm not sure if I made a mistake while handling the errors. Below is my requirements.txt file, and I'm using Python 3.9. Could you help me take a look? Thank you very much.
[requirements.txt](https://github.com/user-attachments/files/17801521/requirements.txt)

**Comment by karanchellani** [comment]
We have updated documentation. Please refer updated documentation, this issue should not arise now.
