### ISSUE TITLE
Chat with own existing neo4j graph either online or locally

### ISSUE THREAD

**Issue by Howie-Arup** [neo4j-labs/llm-graph-builder#889]
Hi, I have my own neo4j graph. I wonder is it doable to chat with my own neo4j graph either online via the UI or locally? Thanks!

**Comment by kartikpersistent** [comment]
Hi @Howie-Arup  you can use [neoconverse](https://neo4j.com/labs/genai-ecosystem/neoconverse/) for communicating existing data but we are planning to integrate that into Knowledge graph builder we will let you know soon.

**Comment by Howie-Arup** [comment]
Thanks @kartikpersistent for your reply! It seems that the certificate is unsecure to access. Just wonder would there be a safer link (as I am accessing it with the company network)? 
![image](https://github.com/user-attachments/assets/7e72abaf-c377-42c5-b6bf-5ea5927c1f05)

**Comment by kartikpersistent** [comment]
In that we are planning for deploying it securely so we will keep posted on that

**Comment by Howie-Arup** [comment]
@kartikpersistent Got it thanks!
