### ISSUE TITLE
Backend URL in front-end via environment

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/llm-graph-builder#9]
- by default should come from environment variable / .env file (using dotenv)

- if not set you can use the logic you have here right now, but probably want to add a check and also test for localhost 
- https://github.com/neo4j-labs/llm-graph-builder/blob/main/frontend/src/utils/utils.ts#L1

**Comment by jexp** [comment]
https://docs.docker.com/compose/environment-variables/set-environment-variables/#:~:text=The%20.env%20file%20should%20be,see%20Syntax%20for%20environment%20files.

**Comment by prakriti-solankey** [comment]
@jexp  , 
How shall we proceed on this ticket , as we can see a PR for review ?
That looks fine to us . We are waiting for your response whether to keep the connection modal or not, to close the PR.
