### ISSUE TITLE
[Enhancement] Default model selection

### ISSUE THREAD

**Issue by msenechal** [neo4j-labs/llm-graph-builder#900]
[The switch](https://github.com/neo4j-labs/llm-graph-builder/blob/main/frontend/src/utils/Constants.ts#L34) currently assumes diffbot exists - but we might not want to use/configure diffbot.
 
It would be better if we just not arbitrarily default a model, either leave it blank at first usage (or default to 1st option in the VITE_LLM_MODELS) , and then, save the selected model as default in the session/browser storage so you don't have to re-select all the time
(and if the model in the session doesn't exist anymore, put it blank for user selection or again default to 1st option)

**Comment by kartikpersistent** [comment]
Hi @jexp what's your suggestion on this?

**Comment by jexp** [comment]
Yes agreed, I think we should only use the configured models. And then provide them in a sensible order so that the UI can select the first one.
