### ISSUE TITLE
Backend fails to merge the chunked files into the merged directory

### ISSUE THREAD

**Issue by MelvinAkothINGUBU** [neo4j-labs/llm-graph-builder#905]
I am calling the /upload and /extract endpoint in my frontend. 
The payload for my upload endpont is as follows: 

**file: (binary)
uri:***
userName: ***
Password: ***
database: ***
chunkNumber: ***
totalChunks: ***
originalname: Data Security Content.docx
model: openai_gpt_3.5****

They are correctly populated of course and the response is as follows: {"status":"Success","message":"Chunk 5/10 saved"}
In the backend:  Chunk File Path: /code/chunks/Data Security Content.docx_part_5

My  extract payload is as follows:

**uri: ***
userName: ***
password: ***
database: ***
source_type: local file
file_name: Data Security Content.docx
source_url: /code/chunks/Data Security Content.docx_part_5
model: openai_gpt_3.5**

However, the merging process fails causing the extract to fail with the below logs:

backend   |   File "/code/src/main.py", line 221, in extract_graph_from_file_local_file
backend   |     file_name, pages, file_extension = get_documents_from_file_by_path(merged_file_path,fileName)
backend   |   File "/code/src/document_sources/local_file.py", line 46, in get_documents_from_file_by_path
backend   |     raise Exception(f'File {file_name} does not exist')
backend   | Exception: File Data Security Content.docx does not exist
backend   | 2024-11-28 07:07:29,387 - gcs file cache: False
backend   | 2024-11-28 07:07:29,392 - Chunk File Path: /code/chunks/Data Security Content.docx_part_5
backend   | 2024-11-28 07:07:32,934 - File path:/code/merged_files/Data Security Content.docx
backend   | 2024-11-28 07:07:32,934 - Process file name :Data Security Content.docx
backend   | 2024-11-28 07:07:32,945 - File Data Security Content.docx does not exist
backend   | 2024-11-28 07:07:33,230 - Deleted File Path: /code/merged_files/Data Security Content.docx and Deleted File Name : Data Security Content.docx
backend   | 2024-11-28 07:07:33,231 - File Failed in extraction: {'message': 'Failed To Process File:Data Security Content.docx or LLM Unable To Parse Content ', 'error_message': 'File Data Security Content.docx does not exist', 'file_name': 'Data Security Content.docx', 'status': 'Failed', 'db_url': 'neo4j+s://716813a8.databases.neo4j.io:7687', 'failed_count': 1, 'source_type': 'local file', 'source_url': '/code/chunks/Data Security Content.docx_part_5', 'wiki_query': None, 'logging_time': '2024-11-28 07:07:33 UTC'}
backend   | Traceback (most recent call last):
backend   |   File "/code/score.py", line 223, in extract_knowledge_graph_from_file
backend   |     uri_latency, result = await extract_graph_from_file_local_file(uri, userName, password, database, model, merged_file_path, file_name, allowedNodes, allowedRelationship, retry_condition)
backend   |   File "/code/src/main.py", line 221, in extract_graph_from_file_local_file
backend   |     file_name, pages, file_extension = get_documents_from_file_by_path(merged_file_path,fileName)
backend   |   File "/code/src/document_sources/local_file.py", line 46, in get_documents_from_file_by_path
backend   |     raise Exception(f'File {file_name} does not exist')
backend   | Exception: File Data Security Content.docx does not exist

**Comment by praveshkumar1988** [comment]
Not able to replicate the issue. As per the logs file already exist at 
backend | 2024-11-28 07:07:32,934 - File path:/code/merged_files/Data Security Content.docx
It should not throw this error.
After merged file all chunks deleted. Please try again and let me know 
FYI, Below env variable should be false. 
GCS_FILE_CACHE = False

**Comment by MelvinAkothINGUBU** [comment]
I figured the file chunks were being deleted before being merged hence the issue. But it has been resolved by pulling the latest changes and restarting the docker container. Thanks!
