### ISSUE TITLE
Environment Configuration: Model Name Format Mismatch Between example.env and constants.py

### ISSUE THREAD

**Issue by SwiftyProjects** [neo4j-labs/llm-graph-builder#910]
## Description:
Found and resolved an issue where LLM model configuration fails silently due to naming convention mismatch.

### Issue:
- example.env uses underscore format: `LLM_MODEL_CONFIG_openai_gpt_3_5`
- constants.py expects hyphen format: `openai-gpt-3.5`
- This mismatch causes NoneType errors during LLM parsing phase

### Impact:
- Document processing fails at LLM parsing stage
- No clear error message indicating configuration issue
- Other functionality (Neo4j, embeddings) works normally

## Solution:
Update .env configuration to use hyphens instead of underscores:

```
# Wrong format:
LLM_MODEL_CONFIG_openai_gpt_3_5="gpt-3.5-turbo-0125,openai_api_key"

# Correct format:
LLM_MODEL_CONFIG_openai-gpt-3.5="gpt-3.5-turbo-0125,openai_api_key"
```

## Suggestion:
Consider:
1. Updating example.env to match constants.py naming convention
2. Adding validation for model name format
3. Improving error message when configuration isn't found

**Comment by aashipandya** [comment]
Hi @SwiftyProjects 
The correct config is 'LLM_MODEL_CONFIG_openai_gpt_3.5' and same value is passed from Ui dropdown i.e. 'openai_gpt_3.5'. MODEL_VERSIONS is constant.py are not used anymore
