### ISSUE TITLE
Duplicate Nodes for varying aliases

### ISSUE THREAD

**Issue by NotYuSheng** [neo4j-labs/llm-graph-builder#912]
![Bucky Barnes](https://github.com/user-attachments/assets/3e5e93f9-1fb4-4d46-907b-1bbca6d82810 "Bucky Barnes")

## Issue
When generating relationship graphs for characters using multiple articles, the node for `Bucky Barnes` appears under three different names:

- James Bucky Barnes
- Bucky Barnes
- James Buchanan Bucky Barnes

This redundancy occurs because different articles reference the same character using slightly different names or aliases. The issue leads to fragmented relationships and an inaccurate graph representation.

## Questions
Is there currently a way to address this issue using the existing features of the graph builder? For example:

- Can nodes be manually merged post-generation?
- Are there configuration options or preprocessing steps to handle name variations before inputting the articles?

**Comment by kartikpersistent** [comment]
Hi @NotYuSheng we are in planning a feature where duplicate or similar nodes will get merged through post processing task it will be in the next release by the way you can merge the duplicate nodes in the graph enhancement tab but it is not automatically happening user needs to choose the nodes to be merged 
![{FEF2BF44-114D-49F5-9C66-732880B49C53}](https://github.com/user-attachments/assets/74d79880-41fe-4562-8b1e-ecdc3290eed2)

**Comment by NotYuSheng** [comment]
I see, thanks for the help!
