### ISSUE TITLE
graphRAG on an existing knowledge graph

### ISSUE THREAD

**Issue by AI7Xiao** [neo4j-labs/llm-graph-builder#928]
Thank you very much for your project, I have learnt a lot of new and innovative things.

If now I have built a knowledge graph in neo4j, how can I use LLM for graphRAG based on this KG in the UI?

Any replies will be greatly appreciated.

**Comment by kartikpersistent** [comment]
Hi @AI7Xiao thanks you so much for your words regarding existing knowledge graph you can refer #889
