### ISSUE TITLE
How to change the embedding model to openai embedding model

### ISSUE THREAD

**Issue by haris525** [neo4j-labs/llm-graph-builder#945]
Hello, I noticed that by default the local app uses the Mini L6 model, and I think the online version does the same, even the one that uses openai, I was wondering which files locally do I need to use my openai embedding model? I know I will have to change the dimension to 1536. Appreciate the help!

Thank you

**Comment by kaustubh-darekar** [comment]
Hi @haris525  you can add these two variable in backend/.env file

OPENAI_API_KEY = "sk-xyz" (fill with openai key)
EMBEDDING_MODEL = "openai"

this will make use of OpenAIEmbeddings() and dimensions will be 1536.  
You can refer load_embedding_model in shared/common_fn.py for more details.

**Comment by haris525** [comment]
> Hi @haris525 you can add these two variable in backend/.env file
> 
> OPENAI_API_KEY = "sk-xyz" (fill with openai key) EMBEDDING_MODEL = "openai"
> 
> this will make use of OpenAIEmbeddings() and dimensions will be 1536. You can refer load_embedding_model in shared/common_fn.py for more details.

perfect! thank you darekar! so by default it uses the ada or the small model, due to the 1536 dimensions. I will give it a try! thank you so much
